"""Auto-generated by rote.adapters.temporal.

Pipeline: bdr-campaign v0.1.0
Source skill: ../skill

DO NOT EDIT BY HAND. Re-run ``rote emit`` to regenerate.

Architecture note: every external_call activity in this file
wraps a deterministic Python function from the ``extracted/``
package. None of them call MCP tools at runtime — the MCP
tool calls from the source skill have been graduated into
direct API calls during the rote emission step.
"""

from __future__ import annotations

from typing import Any

from temporalio import activity


def _serialize(obj: Any) -> Any:
    """Convert pydantic models / dataclasses / lists to plain dicts.

    Activities return JSON-serializable payloads so the workflow
    doesn't carry typed objects through Temporal's history.
    """
    if hasattr(obj, "model_dump"):
        return obj.model_dump(by_alias=True)
    if isinstance(obj, list):
        return [_serialize(x) for x in obj]
    if isinstance(obj, tuple):
        return [_serialize(x) for x in obj]
    if isinstance(obj, dict):
        return {k: _serialize(v) for k, v in obj.items()}
    return obj

@activity.defn(name="target_research")
async def target_research(payload: dict) -> dict:
    """Run external research (Bright Data web search, ClinicalTrials.gov)

    STUB — agent loops require an LLM agent runtime. Implement
    this against the project's preferred agent harness (Anthropic
    Agent SDK, OpenAI Agents SDK, LangGraph, etc.).
    """
    # Tools the agent should be allowed to call inside the loop:
    #   - bright_data_search
    #   - bright_data_scrape
    #   - clinical_trials_search
    #   - airweave_search
    #   - salesforce_query
    raise NotImplementedError("agent_loop activity 'target_research': requires an agent runtime")

@activity.defn(name="taxonomy_lookup")
async def taxonomy_lookup(payload: dict) -> dict:
    """Resolve ZoomInfo IDs for management levels (VP, Director), industries

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.taxonomy`` for implementation.
    """
    from expected.extracted.taxonomy import resolve_taxonomy_ids
    result = await resolve_taxonomy_ids(**payload)
    return _serialize(result)

@activity.defn(name="lead_generation_loop")
async def lead_generation_loop(payload: dict) -> dict:
    """Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo

    STUB — agent loops require an LLM agent runtime. Implement
    this against the project's preferred agent harness (Anthropic
    Agent SDK, OpenAI Agents SDK, LangGraph, etc.).
    """
    # Tools the agent should be allowed to call inside the loop:
    #   - zoominfo_search_contacts
    #   - zoominfo_search_companies
    # Loop body sub-nodes (call these for each iteration):
    #   - enrich_contact_batch
    #   - vet_contact
    raise NotImplementedError("agent_loop activity 'lead_generation_loop': requires an agent runtime")

@activity.defn(name="enrich_contact_batch")
async def enrich_contact_batch(payload: dict) -> dict:
    """Batch enrich contacts via ZoomInfo. Always requests employmentHistory

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.zoominfo`` for implementation.
    """
    # Constants from the IR (extracted from the source skill prose):
    #   batch_size = 10
    #   output_fields = ['firstName', 'lastName', 'jobTitle', 'email', 'phone', 'mobilePhone', 'contactAccuracyScore', 'companyName', 'externalUrls', 'employmentHistory', 'directPhoneDoNotCall', 'mobilePhoneDoNotCall', 'validDate']
    from expected.extracted.zoominfo import enrich_batch
    result = await enrich_batch(**payload)
    return _serialize(result)

@activity.defn(name="vet_contact")
async def vet_contact(payload: dict) -> dict:
    """Apply the red-flags rubric (MSL, biomarker, translational, indication

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this activity, not the workflow.
    """
    from expected.signatures.vet_contact import (
        VetContact,
        VetContactInput,
    )
    judge = VetContact()
    result = await judge.forward(VetContactInput(**payload))
    return result.model_dump(by_alias=True)

@activity.defn(name="hubspot_upsert")
async def hubspot_upsert(payload: dict) -> dict:
    """Batch upsert contacts to HubSpot (create or update by email). Hard

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.hubspot`` for implementation.
    """
    # Constants from the IR (extracted from the source skill prose):
    #   batch_size = 100
    from expected.extracted.hubspot import batch_upsert_contacts
    result = await batch_upsert_contacts(**payload)
    return _serialize(result)

@activity.defn(name="hubspot_create_list")
async def hubspot_create_list(payload: dict) -> dict:
    """Create a static list named after the campaign and add the upserted

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.hubspot`` for implementation.
    """
    # Constants from the IR (extracted from the source skill prose):
    #   add_batch_size = 250
    from expected.extracted.hubspot import create_campaign_list
    result = await create_campaign_list(**payload)
    return _serialize(result)

@activity.defn(name="exclusion_check_dnc")
async def exclusion_check_dnc(payload: dict) -> dict:
    """For each contact, look up \"BDR do not contact\" list memberships.

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.exclusion_checks`` for implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    from expected.extracted.exclusion_checks import check_do_not_contact
    result = await check_do_not_contact(**payload)
    return _serialize(result)

@activity.defn(name="exclusion_check_recent")
async def exclusion_check_recent(payload: dict) -> dict:
    """For each contact, check if they were emailed (outbound) in the last

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.exclusion_checks`` for implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    # Constants from the IR (extracted from the source skill prose):
    #   days_back = 30
    #   direction = 'OUTBOUND'
    from expected.extracted.exclusion_checks import check_recently_emailed
    result = await check_recently_emailed(**payload)
    return _serialize(result)

@activity.defn(name="exclusion_check_sequence")
async def exclusion_check_sequence(payload: dict) -> dict:
    """For each contact, check if they are already enrolled in an active

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.exclusion_checks`` for implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    from expected.extracted.exclusion_checks import check_active_sequence
    result = await check_active_sequence(**payload)
    return _serialize(result)

@activity.defn(name="personalize_email")
async def personalize_email(payload: dict) -> dict:
    """Generate personalized opening line and TA-relevant callout per

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this activity, not the workflow.
    """
    from expected.signatures.personalize_email import (
        PersonalizeEmail,
        PersonalizeEmailInput,
    )
    judge = PersonalizeEmail()
    result = await judge.forward(PersonalizeEmailInput(**payload))
    return result.model_dump(by_alias=True)

@activity.defn(name="create_sales_template")
async def create_sales_template(payload: dict) -> dict:
    """Create or update HubSpot sales templates for the campaign sequence

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.hubspot`` for implementation.
    """
    from expected.extracted.hubspot import upsert_sales_template
    result = await upsert_sales_template(**payload)
    return _serialize(result)

@activity.defn(name="pre_enrollment_report")
async def pre_enrollment_report(payload: dict) -> dict:
    """Generate the final pre-enrollment report (markdown) with totals,

    Graduated from MCP tool call → deterministic API call. See
    ``expected.extracted.report`` for implementation.
    """
    from expected.extracted.report import generate_pre_enrollment_report
    result = await generate_pre_enrollment_report(**payload)
    return _serialize(result)
