"""Auto-generated by rote.adapters.temporal.

Pipeline: bdr-campaign v0.1.0
Source skill: ../skill
Pipeline hash: ada0f771

DO NOT EDIT BY HAND. Re-run ``rote emit`` to regenerate.

Workflow versioning: the registered workflow type name
includes a hash of the pipeline so regenerated workflows
become a new type. In-flight workflows on the old type
continue running the old code; new workflows use the new
code. This is the simplest way to avoid Temporal's
determinism errors when regenerating from a changed skill.
"""

from __future__ import annotations

import asyncio
from datetime import timedelta

from temporalio import workflow
from temporalio.common import RetryPolicy


def _parse_minutes(s: str) -> float:
    """Parse a duration string like '5m', '30s', '7d' into minutes."""
    s = s.strip()
    if s.endswith("ms"):
        return float(s[:-2]) / 60_000
    if s.endswith("s"):
        return float(s[:-1]) / 60
    if s.endswith("m"):
        return float(s[:-1])
    if s.endswith("h"):
        return float(s[:-1]) * 60
    if s.endswith("d"):
        return float(s[:-1]) * 60 * 24
    return float(s)


@workflow.defn(name="BdrCampaign_ada0f771")
class BdrCampaignWorkflow:
    """Compiled workflow for bdr-campaign."""

    def __init__(self) -> None:
        self._contact_review_approved_payload: dict | None = None
        self._bdr_enrollment_complete_payload: dict | None = None

    @workflow.signal(name="contact_review_approved")
    def contact_review_approved(self, payload: dict) -> None:
        """Present the final vetted contact table to the user with a summary of"""
        self._contact_review_approved_payload = payload

    @workflow.signal(name="bdr_enrollment_complete")
    def bdr_enrollment_complete(self, payload: dict) -> None:
        """Present the pre-enrollment report to the BDR. Sequence enrollment"""
        self._bdr_enrollment_complete_payload = payload

    @workflow.run
    async def run(self, pipeline_input: dict) -> dict:
        """End-to-end BDR outreach campaign workflow for pharma/biotech research"""

        # ─── Wave 1 ───
        (
            target_research_result,
            taxonomy_lookup_result,
        ) = await asyncio.gather(
            workflow.execute_activity(
                "target_research",
                {
                    "brief": pipeline_input,
                },
                start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
                retry_policy=RetryPolicy(maximum_attempts=3, backoff_coefficient=2.0),
            ),
            workflow.execute_activity(
                "taxonomy_lookup",
                {
                    "brief": pipeline_input,
                },
                start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
            ),
        )

        # ─── Wave 2 ───
        lead_generation_loop_result = await workflow.execute_activity(
            "lead_generation_loop",
            {
                "brief": pipeline_input,
                "intel": target_research_result,
                "taxonomy": taxonomy_lookup_result,
                "target_quota": pipeline_input["target_quota"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("15m")),
        )

        # ─── Wave 3 ───
        # ─── HITL gate: contact_review_gate ───
        # Workflow suspends here until the 'contact_review_approved' signal
        # arrives. Survives worker restarts; resumes immediately
        # when the signal fires.
        await workflow.wait_condition(
            lambda: self._contact_review_approved_payload is not None
        )
        contact_review_gate_result = self._contact_review_approved_payload

        # ─── Wave 4 ───
        hubspot_upsert_result = await workflow.execute_activity(
            "hubspot_upsert",
            {
                "contacts": contact_review_gate_result["approved_contacts"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("60s")),
            retry_policy=RetryPolicy(maximum_attempts=6, backoff_coefficient=2.0),
        )

        # ─── Wave 5 ───
        hubspot_create_list_result = await workflow.execute_activity(
            "hubspot_create_list",
            {
                "campaign_name": pipeline_input["drug_brand"],
                "contacts": hubspot_upsert_result["upserted"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
            retry_policy=RetryPolicy(maximum_attempts=6, backoff_coefficient=2.0),
        )

        # ─── Wave 6 ───
        exclusion_check_dnc_result = await workflow.execute_activity(
            "exclusion_check_dnc",
            {
                "contacts": hubspot_upsert_result["upserted"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
        )

        # ─── Wave 7 ───
        exclusion_check_recent_result = await workflow.execute_activity(
            "exclusion_check_recent",
            {
                "contacts": exclusion_check_dnc_result["passed"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
        )

        # ─── Wave 8 ───
        exclusion_check_sequence_result = await workflow.execute_activity(
            "exclusion_check_sequence",
            {
                "contacts": exclusion_check_recent_result["passed"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
        )

        # ─── Wave 9 ───
        personalize_email_result = await workflow.execute_activity(
            "personalize_email",
            {
                "contact": exclusion_check_sequence_result["passed"],
                "intel": target_research_result,
                "campaign_type": pipeline_input["campaign_type"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
        )

        # ─── Wave 10 ───
        create_sales_template_result = await workflow.execute_activity(
            "create_sales_template",
            {
                "campaign_name": pipeline_input["drug_brand"],
                "personalizations": personalize_email_result,
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
            retry_policy=RetryPolicy(maximum_attempts=4, backoff_coefficient=2.0),
        )

        # ─── Wave 11 ───
        pre_enrollment_report_result = await workflow.execute_activity(
            "pre_enrollment_report",
            {
                "campaign_name": pipeline_input["drug_brand"],
                "passed_contacts": exclusion_check_sequence_result["passed"],
                "exclusions": exclusion_check_sequence_result["excluded"],
                "template_ids": create_sales_template_result["template_ids"],
            },
            start_to_close_timeout=timedelta(minutes=_parse_minutes("5m")),
        )

        # ─── Wave 12 ───
        # ─── HITL gate: manual_enrollment_handoff ───
        # Workflow suspends here until the 'bdr_enrollment_complete' signal
        # arrives. Survives worker restarts; resumes immediately
        # when the signal fires.
        await workflow.wait_condition(
            lambda: self._bdr_enrollment_complete_payload is not None
        )
        manual_enrollment_handoff_result = self._bdr_enrollment_complete_payload

        return {
            "manual_enrollment_handoff": manual_enrollment_handoff_result,
        }
