"""Typed LLM signature: personalize_email

Generate personalized opening line and TA-relevant callout per

Auto-generated by rote.adapters.dbos from the IR's ``signature_spec``.
The non-determinism lives inside this module; the workflow step that
calls it stays a checkpointed, retryable unit.

DO NOT EDIT BY HAND. Re-run ``rote emit --runtime dbos`` to regenerate.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class EmploymentEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    company: str
    title: str
    start_year: int | None = None
    end_year: int | None = None


class EnrichedContact(BaseModel):
    """A contact after ZoomInfo enrichment with full employment history."""

    model_config = ConfigDict(extra="forbid")

    zoominfo_id: str
    first_name: str
    last_name: str
    job_title: str
    company_name: str
    email: str | None = None
    phone: str | None = None
    mobile_phone: str | None = None
    accuracy_score: int = 0
    linkedin_url: str | None = None
    employment_history: list[EmploymentEntry] | None = None
    direct_phone_dnc: bool = False
    mobile_phone_dnc: bool = False


ContactTier = Literal["ideal", "strong", "good"]


class VettedContact(BaseModel):
    """A contact that survived the LLM vetting loop."""

    model_config = ConfigDict(extra="forbid")

    contact: EnrichedContact
    tier: ContactTier
    relevance_evidence: str


class IntelBrief(BaseModel):
    """Working context produced by Phase 1.5 target research."""

    model_config = ConfigDict(extra="forbid")

    pipeline_summary: str
    rwe_signals: list[str] | None = None
    key_programs: list[str] | None = None
    prior_interactions: str = ""
    relevant_experience: str = ""
    messaging_angles: list[str] | None = None


CampaignType = Literal["drug-specific", "condition-specific", "general-capabilities"]


class PersonalizeEmailInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    contact: VettedContact
    intel: IntelBrief
    campaign_type: CampaignType


class PersonalizeEmailOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    opening_line: str
    ta_callout: str


PROMPT = (
    "Generate a personalized opening line and TA-relevant callout for an outreach email.\n"
    "\nLead with a specific observation about this contact's work \u2014 never generic. G"
    "round the TA callout in our validated experience in the indication.\n\nContact: {{ c"
    "ontact }}\nIntel: {{ intel }}\nCampaign type: {{ campaign_type }}\n\nReturn both fie"
    "lds via the structured output tool."
)

TOOL_DESCRIPTION = "Generate personalized opening line and TA-relevant callout per"

OUTPUT_JSON_SCHEMA: dict[str, Any] = json.loads(
    "{\"additionalProperties\":false,\"properties\":{\"opening_line\":{\"title\":\"Openin"
    "g Line\",\"type\":\"string\"},\"ta_callout\":{\"title\":\"Ta Callout\",\"type\":\"st"
    "ring\"}},\"required\":[\"opening_line\",\"ta_callout\"],\"title\":\"PersonalizeEmail"
    "Output\",\"type\":\"object\"}"
)

# Operator overrides: change the model or point at a different
# endpoint (proxy, gateway, OpenAI-compatible server) without
# re-emitting. Unset means the default below / the vendor's endpoint.
MODEL = os.environ.get("ROTE_MODEL_PERSONALIZE_EMAIL", "claude-sonnet-4-6")
BASE_URL = os.environ.get("ROTE_BASE_URL_PERSONALIZE_EMAIL")


def _interpolate(template: str, variables: dict[str, Any]) -> str:
    """Resolve ``{{ dotted.path }}`` placeholders against the input dict.

    An unresolvable placeholder raises instead of interpolating "" —
    a hole in a judge prompt produces confident garbage that is far
    harder to debug than a KeyError naming the missing variable.
    """

    def _resolve(match: re.Match[str]) -> str:
        path = match.group(1)
        value: Any = variables
        for part in path.split("."):
            if not isinstance(value, dict) or part not in value:
                raise KeyError(
                    f"prompt template references {{{{ {path} }}}} but the "
                    f"input has no such field; available top-level keys: "
                    f"{sorted(variables)}"
                )
            value = value[part]
        if value is None:
            return ""
        return value if isinstance(value, str) else json.dumps(value, default=str)

    return re.sub(r"\{\{\s*([\w.]+)\s*\}\}", _resolve, template)


class PersonalizeEmail:
    """Typed LLM judge for personalize_email (Anthropic structured output)."""

    def forward(self, inputs: PersonalizeEmailInput) -> PersonalizeEmailOutput:
        # Which provider serves this call — and who is billed for it —
        # is resolved at runtime; see signatures/_rote_inference.py.
        from signatures._rote_inference import call_judge

        payload = call_judge(
            node_id="personalize_email",
            client="anthropic",
            model=MODEL,
            base_url=BASE_URL,
            prompt=_interpolate(PROMPT, inputs.model_dump(by_alias=True)),
            output_schema=OUTPUT_JSON_SCHEMA,
            tool_description=TOOL_DESCRIPTION,
        )
        return PersonalizeEmailOutput.model_validate(payload)
