"""Typed LLM signature: vet_contact

Apply the red-flags rubric (MSL, biomarker, translational, indication

Auto-generated by rote.adapters.dbos from the IR's ``signature_spec``.
The non-determinism lives inside this module; the workflow step that
calls it stays a checkpointed, retryable unit.

DO NOT EDIT BY HAND. Re-run ``rote emit --runtime dbos`` to regenerate.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class EmploymentEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    company: str
    title: str
    start_year: int | None = None
    end_year: int | None = None


class EnrichedContact(BaseModel):
    """A contact after ZoomInfo enrichment with full employment history."""

    model_config = ConfigDict(extra="forbid")

    zoominfo_id: str
    first_name: str
    last_name: str
    job_title: str
    company_name: str
    email: str | None = None
    phone: str | None = None
    mobile_phone: str | None = None
    accuracy_score: int = 0
    linkedin_url: str | None = None
    employment_history: list[EmploymentEntry] | None = None
    direct_phone_dnc: bool = False
    mobile_phone_dnc: bool = False


CampaignType = Literal["drug-specific", "condition-specific", "general-capabilities"]


JobFocus = Literal["medical", "rwe", "heor", "clinical-development"]


class CampaignBrief(BaseModel):
    """Top-level pipeline input — one campaign, one drug, one indication."""

    model_config = ConfigDict(extra="forbid")

    drug_brand: str
    drug_generic: str
    condition_full: str
    condition_acronym: str
    therapeutic_area: str
    manufacturer: str
    campaign_type: CampaignType
    target_quota: int
    job_focus: JobFocus | None = None


class IntelBrief(BaseModel):
    """Working context produced by Phase 1.5 target research."""

    model_config = ConfigDict(extra="forbid")

    pipeline_summary: str
    rwe_signals: list[str] | None = None
    key_programs: list[str] | None = None
    prior_interactions: str = ""
    relevant_experience: str = ""
    messaging_angles: list[str] | None = None


class VetContactInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    contact: EnrichedContact
    brief: CampaignBrief
    intel: IntelBrief


VetDecision = Literal["keep", "discard"]


ContactTier = Literal["ideal", "strong", "good"]


DiscardReason = Literal[
    "indication_mismatch",
    "msl_role",
    "biomarker_discovery",
    "translational",
    "sales_commercial",
    "ops_strategy",
    "program_management",
    "low_accuracy",
    "no_valid_email",
    "other",
]


class VetContactOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    decision: VetDecision
    tier: ContactTier | None = None
    discard_reason: DiscardReason | None = None
    relevance_evidence: str


PROMPT = (
    "You are vetting a contact for a BDR outreach campaign.\n\nApply this rubric:\n- Disc"
    "ard if job title indicates MSL, Biomarker/Discovery, Translational Research, Sales/C"
    "ommercial, Operations/Strategy, or Program Management.\n- Discard on indication mism"
    "atch with the campaign therapeutic area.\n- Tier surviving contacts: ideal / strong "
    "/ good based on RWE/HEOR signal density.\n\nCore test: would this person commission,"
    " design, or approve a real-world evidence study?\n\nContact: {{ contact }}\nCampaign"
    " brief: {{ brief }}\nIntel brief: {{ intel }}\n\nReturn your decision via the struct"
    "ured output tool."
)

TOOL_DESCRIPTION = "Apply the red-flags rubric (MSL, biomarker, translational, indication"

OUTPUT_JSON_SCHEMA: dict[str, Any] = json.loads(
    "{\"$defs\":{\"ContactTier\":{\"enum\":[\"ideal\",\"strong\",\"good\"],\"title\":\"Co"
    "ntactTier\",\"type\":\"string\"},\"DiscardReason\":{\"enum\":[\"indication_mismatch\""
    ",\"msl_role\",\"biomarker_discovery\",\"translational\",\"sales_commercial\",\"ops_s"
    "trategy\",\"program_management\",\"low_accuracy\",\"no_valid_email\",\"other\"],\"ti"
    "tle\":\"DiscardReason\",\"type\":\"string\"},\"VetDecision\":{\"enum\":[\"keep\",\"d"
    "iscard\"],\"title\":\"VetDecision\",\"type\":\"string\"}},\"additionalProperties\":f"
    "alse,\"properties\":{\"decision\":{\"$ref\":\"#/$defs/VetDecision\"},\"tier\":{\"any"
    "Of\":[{\"$ref\":\"#/$defs/ContactTier\"},{\"type\":\"null\"}],\"default\":null},\"di"
    "scard_reason\":{\"anyOf\":[{\"$ref\":\"#/$defs/DiscardReason\"},{\"type\":\"null\"}]"
    ",\"default\":null},\"relevance_evidence\":{\"title\":\"Relevance Evidence\",\"type\""
    ":\"string\"}},\"required\":[\"decision\",\"relevance_evidence\"],\"title\":\"VetCont"
    "actOutput\",\"type\":\"object\"}"
)

# Operator overrides: change the model or point at a different
# endpoint (proxy, gateway, OpenAI-compatible server) without
# re-emitting. Unset means the default below / the vendor's endpoint.
MODEL = os.environ.get("ROTE_MODEL_VET_CONTACT", "claude-sonnet-4-6")
BASE_URL = os.environ.get("ROTE_BASE_URL_VET_CONTACT")


def _interpolate(template: str, variables: dict[str, Any]) -> str:
    """Resolve ``{{ dotted.path }}`` placeholders against the input dict.

    An unresolvable placeholder raises instead of interpolating "" —
    a hole in a judge prompt produces confident garbage that is far
    harder to debug than a KeyError naming the missing variable.
    """

    def _resolve(match: re.Match[str]) -> str:
        path = match.group(1)
        value: Any = variables
        for part in path.split("."):
            if not isinstance(value, dict) or part not in value:
                raise KeyError(
                    f"prompt template references {{{{ {path} }}}} but the "
                    f"input has no such field; available top-level keys: "
                    f"{sorted(variables)}"
                )
            value = value[part]
        if value is None:
            return ""
        return value if isinstance(value, str) else json.dumps(value, default=str)

    return re.sub(r"\{\{\s*([\w.]+)\s*\}\}", _resolve, template)


def _log_usage(response: Any) -> None:
    """Append token usage as JSONL to $ROTE_USAGE_LOG, if set."""
    path = os.environ.get("ROTE_USAGE_LOG")
    if not path:
        return
    try:
        usage = getattr(response, "usage", None)
        record = {
            "node": "vet_contact",
            "model": MODEL,
            "input_tokens": getattr(usage, "input_tokens", None),
            "output_tokens": getattr(usage, "output_tokens", None),
        }
        with open(path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")
    except OSError:
        pass


class VetContact:
    """Typed LLM judge for vet_contact (Anthropic structured output)."""

    def forward(self, inputs: VetContactInput) -> VetContactOutput:
        # Lazy import: the SDK is only needed at call time, and the
        # module stays importable in environments without it.
        import anthropic

        client = anthropic.Anthropic(base_url=BASE_URL)
        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            tools=[
                {
                    "name": "vet_contact",
                    "description": TOOL_DESCRIPTION,
                    "input_schema": OUTPUT_JSON_SCHEMA,
                }
            ],
            tool_choice={"type": "tool", "name": "vet_contact"},
            messages=[
                {
                    "role": "user",
                    "content": _interpolate(PROMPT, inputs.model_dump(by_alias=True)),
                }
            ],
        )
        _log_usage(response)
        for block in response.content:
            if block.type == "tool_use":
                return VetContactOutput.model_validate(block.input)
        raise RuntimeError(
            "LLM did not return a tool_use block for vet_contact"
        )
