"""Auto-generated by rote.adapters.dbos.

Pipeline: rote-compile v0.1.0
Source skill: ../../../../../skills/rote-compile
Pipeline hash: dff14b77

DO NOT EDIT BY HAND. Re-run ``rote emit --runtime dbos`` to regenerate.

Workflow versioning: the registered workflow name includes a hash of
the pipeline so regenerated pipelines become a new workflow type.
In-flight workflows recover onto the code they started with (DBOS
recovers by workflow name + application_version); new starts use the
new code.

Architecture note: every step in this file wraps a deterministic
function from ``extracted/`` or a typed LLM signature from
``signatures/``. None of them call MCP tools at runtime — the MCP
tool calls from the source skill were compiled into direct API
calls during the rote emission step.
"""

from __future__ import annotations

import json
import os
import sys
import threading
from pathlib import Path
from typing import Any

from dbos import DBOS, DBOSConfig, Queue

# ───────── DBOS configuration ─────────
#
# Local dev runs on SQLite (zero infrastructure). Production should
# point DBOS_SYSTEM_DATABASE_URL at Postgres — SQLite is
# single-process only.
_APP_DIR = Path(__file__).resolve().parent

config: DBOSConfig = {
    "name": "rote-compile",
    "system_database_url": os.environ.get(
        "DBOS_SYSTEM_DATABASE_URL",
        f"sqlite:///{_APP_DIR / 'rote-compile.dbos.sqlite'}",
    ),
    # The admin server (port 3001) is opt-in; enable it when you
    # want the DBOS console / management API.
    "run_admin_server": False,
}
DBOS(config=config)

# Parallel waves fan out onto this queue; each enqueued step runs as
# a one-step workflow with its own durable handle.
queue = Queue("rote-compile-queue")


def _serialize(obj: Any) -> Any:
    """Convert pydantic models / tuples to plain JSON-safe values.

    Steps return JSON-serializable payloads so workflow state stays
    portable across the system database.
    """
    if hasattr(obj, "model_dump"):
        return obj.model_dump(by_alias=True)
    if isinstance(obj, (list, tuple)):
        return [_serialize(x) for x in obj]
    if isinstance(obj, dict):
        return {k: _serialize(v) for k, v in obj.items()}
    return obj


def _fan_out_list(value: object, node_id: str, ref: str) -> list:
    """The list a fan_out node dispatches over.

    Iterating a missing key raises "'NoneType' object is not iterable",
    which names neither the node nor the reference — in generated code
    that is close to undebuggable, and the cause is almost always an
    upstream node that didn't return the key the IR says it does. The
    TypeScript runtimes emit the same guard (`fanOutList`), so a missing
    key reports identically on every target.
    """
    if not isinstance(value, list):
        raise TypeError(
            f"fan_out node {node_id!r} expected a list from {ref!r}, got "
            f"{type(value).__name__}. The upstream node must return that "
            f"key as a list."
        )
    return value


@DBOS.step(name="read_skill_bundle", retries_allowed=True, max_attempts=4, backoff_rate=2.0)
def read_skill_bundle(payload: dict) -> dict:
    """Read SKILL.md and all files under references/ from the skill directory.

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.file_reader`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    # retry_on categories from the IR: network, io_error. DBOS retries any
    # exception; narrow with @DBOS.step(should_retry=...) if needed.
    # IR timeout '30s': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.file_reader import read_skill_bundle

    return _serialize(read_skill_bundle(**payload))


@DBOS.step(name="detect_entry_point")
def detect_entry_point(payload: dict) -> dict:
    """Determine which phases to run and the compilation mode from CLI flags

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.entry_point`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    from extracted.entry_point import detect_entry_point

    return _serialize(detect_entry_point(**payload))


@DBOS.step(name="identify_steps", retries_allowed=True, max_attempts=3, backoff_rate=2.0)
def identify_steps(payload: dict) -> dict:
    """Read the full skill bundle and identify every distinct pipeline step.

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this step, not the workflow.
    """
    # IR timeout '3m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures.identify_steps import IdentifySteps, IdentifyStepsInput

    judge = IdentifySteps()
    return judge.forward(IdentifyStepsInput(**payload)).model_dump(by_alias=True)


@DBOS.step(name="classify_step", retries_allowed=True, max_attempts=3, backoff_rate=2.0)
def classify_step(payload: dict) -> dict:
    """Apply the five-kind classification rubric to a single identified step

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this step, not the workflow.
    """
    # IR timeout '2m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures.classify_step import ClassifyStep, ClassifyStepInput

    judge = ClassifyStep()
    return judge.forward(ClassifyStepInput(**payload)).model_dump(by_alias=True)


@DBOS.step(name="codification_scan")
def codification_scan(payload: dict) -> dict:
    """Scan the source skill for every crystallizable pattern: literal Python

    Agent loop — bounded, tool-restricted, and real: the provider
    (Claude subscription / API key / rote cloud) is resolved at
    runtime by signatures/_rote_inference.py.
    """
    # IR timeout '10m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures._rote_inference import run_agent_loop

    return run_agent_loop(
        node_id="codification_scan",
        description=(
            "Scan the source skill for every crystallizable pattern: literal Python\nor p"
            "seudocode, fixed constants, MANDATORY checks, fixed string templates,\nbatch"
            "ing loops, taxonomy lookups, and numeric thresholds. For each step\nclassifi"
            "ed as pure_function or external_call, write a contract-documented\nstub in t"
            "he extracted/ directory. Returns a codification plan listing\nevery extracti"
            "on and the constants lifted. The agent reads reference files\nin the order: "
            "references/*.md first (highest crystallization density),\nthen SKILL.md.\n"
        ),
        task=json.dumps(payload, default=str),
        model=os.environ.get("ROTE_MODEL_CODIFICATION_SCAN", "claude-sonnet-4-6"),
        tools=["read_file", "write_file", "search_file_content"],
        tool_servers={"read_file": "filesystem", "search_file_content": "filesystem", "write_file": "filesystem"},
        max_iterations=20,
        termination=(
            "Every step with kind pure_function or external_call has a corresponding extr"
            "acted/*.py stub with a documented contract."
        ),
    )


@DBOS.step(name="design_signatures")
def design_signatures(payload: dict) -> dict:
    """For each classified llm_judge step, design a typed signature following

    Agent loop — bounded, tool-restricted, and real: the provider
    (Claude subscription / API key / rote cloud) is resolved at
    runtime by signatures/_rote_inference.py.
    """
    # IR timeout '10m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures._rote_inference import run_agent_loop

    return run_agent_loop(
        node_id="design_signatures",
        description=(
            "For each classified llm_judge step, design a typed signature following\nthe "
            "extraction procedure: enumerate the decision space, design input and\noutput"
            " Pydantic models with enum-bounded fields, lift hard numeric\nthresholds int"
            "o pre-filters, write signatures/<node_id>.py, and scaffold\nevals/<node_id>."
            "jsonl with 3-5 seed examples sourced directly from the\nskill's rubric. Also"
            " populate the signature_spec block for each judge\n(JSON Schema + prompt tem"
            "plate) for cross-runtime support. Never sets\ntemperature in signature_spec."
            "\n"
        ),
        task=json.dumps(payload, default=str),
        model=os.environ.get("ROTE_MODEL_DESIGN_SIGNATURES", "claude-sonnet-4-6"),
        tools=["read_file", "write_file"],
        tool_servers={"read_file": "filesystem", "write_file": "filesystem"},
        max_iterations=15,
        termination=(
            "Every step with kind llm_judge has a signatures/*.py file and a evals/*.json"
            "l seed file with at least 3 examples."
        ),
    )


@DBOS.step(name="estimate_eval_turns", retries_allowed=True, max_attempts=3, backoff_rate=2.0)
def estimate_eval_turns(payload: dict) -> dict:
    """Estimate how many agent turns a step consumes when the skill runs as raw

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this step, not the workflow.
    """
    # IR timeout '2m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures.estimate_eval_turns import EstimateEvalTurns, EstimateEvalTurnsInput

    judge = EstimateEvalTurns()
    return judge.forward(EstimateEvalTurnsInput(**payload)).model_dump(by_alias=True)


@DBOS.step(name="assemble_ir")
def assemble_ir(payload: dict) -> dict:
    """Synthesize all prior work into a complete, valid pipeline.yaml. Uses the

    Agent loop — bounded, tool-restricted, and real: the provider
    (Claude subscription / API key / rote cloud) is resolved at
    runtime by signatures/_rote_inference.py.
    """
    # IR timeout '15m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures._rote_inference import run_agent_loop

    return run_agent_loop(
        node_id="assemble_ir",
        description=(
            "Synthesize all prior work into a complete, valid pipeline.yaml. Uses the\ncl"
            "assified steps, codification plan (extracted stubs), signature designs,\nful"
            "l skill bundle, and entry-point config. Makes judgment calls about:\ndata-fl"
            "ow bindings (inputs:), timeouts, retry policies, mandatory flags,\nconstants"
            ", fan_out relationships, and entry/exit nodes. Writes\npipeline.yaml to the "
            "work directory. Must pass the Phase 6 checklist\nbefore terminating: every p"
            "ure_function/external_call has impl:, every\nllm_judge has signature: and si"
            "gnature_spec:, every agent_loop has\ntools:, every hitl_gate has signal:, al"
            "l node references resolve.\n"
        ),
        task=json.dumps(payload, default=str),
        model=os.environ.get("ROTE_MODEL_ASSEMBLE_IR", "claude-sonnet-4-6"),
        tools=["read_file", "write_file"],
        tool_servers={"read_file": "filesystem", "write_file": "filesystem"},
        max_iterations=5,
        termination=(
            "pipeline.yaml written and passes rote.ir.load_pipeline() validation with no "
            "errors. Phase 6 checklist satisfied."
        ),
    )


@DBOS.step(name="write_eval_sidecar")
def write_eval_sidecar(payload: dict) -> dict:
    """Render eval.yaml from the per-step turn estimates produced by

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.eval_sidecar_writer`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    # IR timeout '10s': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.eval_sidecar_writer import write_eval_sidecar

    return _serialize(write_eval_sidecar(**payload))


@DBOS.step(name="validate_ir", retries_allowed=True, max_attempts=2, backoff_rate=1.0)
def validate_ir(payload: dict) -> dict:
    """Load and validate the pipeline.yaml written by assemble_ir using

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.ir_validator`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    # IR timeout '30s': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.ir_validator import validate_ir

    return _serialize(validate_ir(**payload))


@DBOS.step(name="invoke_adapter", retries_allowed=True, max_attempts=3, backoff_rate=2.0)
def invoke_adapter(payload: dict) -> dict:
    """Run `rote emit <pipeline_yaml> --runtime <runtime> --out <out_dir>` to

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.adapter_invoker`` for the implementation.
    """
    # retry_on categories from the IR: network, subprocess_error. DBOS retries any
    # exception; narrow with @DBOS.step(should_retry=...) if needed.
    # IR timeout '5m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.adapter_invoker import invoke_adapter

    return _serialize(invoke_adapter(**payload))


@DBOS.step(name="write_compile_report")
def write_compile_report(payload: dict) -> dict:
    """Render compile-report.md from the full compilation results. Covers:

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.compile_report_renderer`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    # IR timeout '30s': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.compile_report_renderer import write_compile_report

    return _serialize(write_compile_report(**payload))


@DBOS.workflow(name="RoteCompile_dff14b77")
def run_pipeline(pipeline_input: dict) -> dict:
    """Compile an Anthropic-style skill bundle (SKILL.md + references/) into a"""

    # ─── Wave 1 ───
    # Parallel fan-out: enqueue every node in the wave, then
    # join. Each enqueued step runs as its own one-step
    # workflow; get_result() blocks durably.
    detect_entry_point_handle = queue.enqueue(
        detect_entry_point,
        {
            "report_only": pipeline_input["report_only"],
            "update": pipeline_input["update"],
        },
    )
    read_skill_bundle_handle = queue.enqueue(
        read_skill_bundle,
        {
            "skill_dir": pipeline_input["skill_dir"],
        },
    )
    detect_entry_point_result = detect_entry_point_handle.get_result()
    read_skill_bundle_result = read_skill_bundle_handle.get_result()

    # ─── Wave 2 ───
    identify_steps_result = identify_steps(
        {
            "skill_md": read_skill_bundle_result["skill_md"],
            "reference_files": read_skill_bundle_result["reference_files"],
        }
    )

    # ─── Wave 3 ───
    # fan_out: classify_step runs once per element of the bound
    # list, each as its own enqueued durable step.
    classify_step_payloads = [
        {"step": _item, "reference_files": read_skill_bundle_result["reference_files"], "skill_md": read_skill_bundle_result["skill_md"]}
        for _item in _fan_out_list(
            identify_steps_result["steps"],
            "classify_step",
            "identify_steps.output.steps",
        )
    ]
    classify_step_handles = [queue.enqueue(classify_step, _p) for _p in classify_step_payloads]
    classify_step_result = [_h.get_result() for _h in classify_step_handles]

    # ─── Wave 4 ───
    # Parallel fan-out: enqueue every node in the wave, then
    # join. Each enqueued step runs as its own one-step
    # workflow; get_result() blocks durably.
    codification_scan_handle = queue.enqueue(
        codification_scan,
        {
            "classified_steps": classify_step_result,
            "skill_bundle": read_skill_bundle_result,
        },
    )
    design_signatures_handle = queue.enqueue(
        design_signatures,
        {
            "classified_steps": classify_step_result,
            "skill_bundle": read_skill_bundle_result,
        },
    )
    codification_scan_result = codification_scan_handle.get_result()
    design_signatures_result = design_signatures_handle.get_result()
    # fan_out: estimate_eval_turns runs once per element of the bound
    # list, each as its own enqueued durable step.
    estimate_eval_turns_payloads = [
        {"step": _item, "skill_md": read_skill_bundle_result["skill_md"]}
        for _item in _fan_out_list(
            classify_step_result,
            "estimate_eval_turns",
            "classify_step.output",
        )
    ]
    estimate_eval_turns_handles = [queue.enqueue(estimate_eval_turns, _p) for _p in estimate_eval_turns_payloads]
    estimate_eval_turns_result = [_h.get_result() for _h in estimate_eval_turns_handles]

    # ─── Wave 5 ───
    # Parallel fan-out: enqueue every node in the wave, then
    # join. Each enqueued step runs as its own one-step
    # workflow; get_result() blocks durably.
    assemble_ir_handle = queue.enqueue(
        assemble_ir,
        {
            "classified_steps": classify_step_result,
            "codification_plan": codification_scan_result,
            "signature_designs": design_signatures_result,
            "skill_bundle": read_skill_bundle_result,
            "entry_config": detect_entry_point_result,
        },
    )
    write_eval_sidecar_handle = queue.enqueue(
        write_eval_sidecar,
        {
            "turn_estimates": estimate_eval_turns_result,
            "classified_steps": classify_step_result,
            "out_dir": pipeline_input["out_dir"],
            "source_skill_dir": pipeline_input["skill_dir"],
        },
    )
    assemble_ir_result = assemble_ir_handle.get_result()
    write_eval_sidecar_result = write_eval_sidecar_handle.get_result()

    # ─── Wave 6 ───
    validate_ir_result = validate_ir(
        {
            "pipeline_yaml_path": assemble_ir_result["pipeline_yaml_path"],
        }
    )

    # ─── Wave 7 ───
    # Parallel fan-out: enqueue every node in the wave, then
    # join. Each enqueued step runs as its own one-step
    # workflow; get_result() blocks durably.
    invoke_adapter_handle = queue.enqueue(
        invoke_adapter,
        {
            "pipeline_yaml_path": assemble_ir_result["pipeline_yaml_path"],
            "runtime": pipeline_input["runtime"],
            "out_dir": pipeline_input["out_dir"],
            "report_only": pipeline_input["report_only"],
        },
    )
    write_compile_report_handle = queue.enqueue(
        write_compile_report,
        {
            "classified_steps": classify_step_result,
            "codification_plan": codification_scan_result,
            "signature_designs": design_signatures_result,
            "validation_result": validate_ir_result,
            "out_dir": pipeline_input["out_dir"],
            "skill_dir": pipeline_input["skill_dir"],
        },
    )
    invoke_adapter_result = invoke_adapter_handle.get_result()
    write_compile_report_result = write_compile_report_handle.get_result()

    return {
        "write_compile_report": write_compile_report_result,
        "write_eval_sidecar": write_eval_sidecar_result,
        "invoke_adapter": invoke_adapter_result,
    }


if __name__ == "__main__":
    # Launch DBOS (connects to the system database, starts queue
    # workers and recovery). Two modes:
    #
    #   python main.py --serve
    #       Run as a long-lived worker: execute runs enqueued
    #       externally (`rote serve` MCP tools / DBOSClient.enqueue)
    #       against the same system database. This is what
    #       `dbos start` and production deployments run.
    #
    #   python main.py '{"your": "input"}'
    #       Start one pipeline run with the input from argv[1]
    #       (JSON) and block until it completes.
    #
    # HITL gates are resumed from another process either way — see
    # README.md.
    DBOS.launch()
    try:
        if "--serve" in sys.argv[1:]:
            print("serving: waiting for enqueued runs (Ctrl-C to stop)", file=sys.stderr)
            threading.Event().wait()
        else:
            pipeline_input = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
            handle = DBOS.start_workflow(run_pipeline, pipeline_input)
            print(f"workflow started: {handle.workflow_id}", file=sys.stderr)
            print(json.dumps(handle.get_result(), indent=2, default=str))
    finally:
        DBOS.destroy()
