/**
 * Auto-generated by rote.adapters.cloudflare.
 *
 * Default fetch handler. Creates a workflow instance from the request
 * body and returns the instance id + status. Replace with your own
 * trigger surface (cron, queue consumer, etc.) as needed.
 */

import { BdrCampaignWorkflow, type Env, type Params } from "./workflow";

export { BdrCampaignWorkflow };

export default {
    async fetch(req: Request, env: Env): Promise<Response> {
        const raw = await req.json().catch(() => ({}));
        const params = (raw ?? {}) as Params;
        const instance = await env.PIPELINE.create({ params });
        return Response.json({
            id: instance.id,
            status: await instance.status(),
        });
    },
} satisfies ExportedHandler<Env>;
