/**
 * Auto-generated by rote.adapters.cloudflare.
 *
 * Driver surface for the emitted workflow — the routes `rote run`
 * (and `wrangler dev` users) drive:
 *
 *   POST /  or  /start        create an instance (body = Params)
 *   GET  /healthz             liveness probe
 *   GET  /status/<id>         instance status
 *   POST /event/<id>/<type>   deliver a HITL gate event
 *
 * Replace with your own trigger surface (cron, queue consumer,
 * etc.) as needed.
 */

import { BdrCampaignWorkflow, type Env, type Params } from "./workflow";

export { BdrCampaignWorkflow };

export default {
    async fetch(req: Request, env: Env): Promise<Response> {
        const url = new URL(req.url);
        if (url.pathname === "/healthz") {
            return Response.json({ ok: true });
        }
        if (req.method === "POST" && (url.pathname === "/" || url.pathname === "/start")) {
            const raw = await req.json().catch(() => ({}));
            const params = (raw ?? {}) as Params;
            const instance = await env.PIPELINE.create({ params });
            return Response.json({
                id: instance.id,
                status: await instance.status(),
            });
        }
        let m = url.pathname.match(/^\/status\/([^/]+)$/);
        if (m) {
            const instance = await env.PIPELINE.get(m[1]);
            return Response.json(await instance.status());
        }
        m = url.pathname.match(/^\/event\/([^/]+)\/([^/]+)$/);
        if (m && req.method === "POST") {
            const instance = await env.PIPELINE.get(m[1]);
            const payload = await req.json().catch(() => ({}));
            await instance.sendEvent({ type: m[2], payload });
            return Response.json({ ok: true });
        }
        return new Response("not found", { status: 404 });
    },
} satisfies ExportedHandler<Env>;
