/**
 * Auto-generated by rote.adapters.cloudflare.
 *
 * Pipeline: bdr-campaign v0.1.0
 * Source skill: ../../skill
 * Pipeline hash: ac861059
 *
 * DO NOT EDIT BY HAND. Re-run `rote emit --runtime cloudflare` to regenerate.
 *
 * Architecture note: every external_call step in this workflow wraps a
 * deterministic API call from the `extracted/` modules. None of them call
 * MCP tools at runtime — those calls were graduated into direct API calls
 * during the rote emission step.
 */

import {
    WorkflowEntrypoint,
    WorkflowEvent,
    WorkflowStep,
} from "cloudflare:workers";

import { targetResearch } from "./extracted/target_research";
import { taxonomyLookup } from "./extracted/taxonomy_lookup";
import { leadGenerationLoop } from "./extracted/lead_generation_loop";
import { enrichContactBatch } from "./extracted/enrich_contact_batch";
import { vetContact } from "./signatures/vet_contact";
import { hubspotUpsert } from "./extracted/hubspot_upsert";
import { hubspotCreateList } from "./extracted/hubspot_create_list";
import { exclusionCheckDnc } from "./extracted/exclusion_check_dnc";
import { exclusionCheckRecent } from "./extracted/exclusion_check_recent";
import { exclusionCheckSequence } from "./extracted/exclusion_check_sequence";
import { personalizeEmail } from "./signatures/personalize_email";
import { createSalesTemplate } from "./extracted/create_sales_template";
import { preEnrollmentReport } from "./extracted/pre_enrollment_report";

export interface Env {
    ANTHROPIC_API_KEY: string;
    OPENAI_API_KEY?: string;
    PIPELINE: Workflow<Params>;
}

export type Params = Record<string, unknown>;

export class BdrCampaignWorkflow extends WorkflowEntrypoint<Env, Params> {
    async run(event: WorkflowEvent<Params>, step: WorkflowStep) {
        // ─── Wave 1 ───
        const target_research_result = await step.do(
            "target_research",
            { retries: { limit: 2, delay: "5 seconds", backoff: "exponential" }, timeout: "5 minutes" },
            async () => targetResearch({}, this.env),
        );
        const taxonomy_lookup_result = await step.do(
            "taxonomy_lookup",
            { timeout: "10 minutes" },
            async () => taxonomyLookup({}),
        );

        // ─── Wave 2 ───
        const lead_generation_loop_result = await step.do(
            "lead_generation_loop",
            { timeout: "15 minutes" },
            async () => leadGenerationLoop({}, this.env),
        );

        // ─── Wave 3 ───
        // ─── HITL gate: contact_review_gate ───
        // Workflow suspends here until an event of type 'contact_review_approved'
        // arrives. Survives hibernation; events that arrive before this
        // line is reached are buffered and delivered when reached.
        const contact_review_gate_event = await step.waitForEvent<any>(
            "contact_review_gate",
            { type: "contact_review_approved", timeout: "7 days" },
        );
        const contact_review_gate_result = contact_review_gate_event.payload;

        // ─── Wave 4 ───
        const hubspot_upsert_result = await step.do(
            "hubspot_upsert",
            { retries: { limit: 5, delay: "5 seconds", backoff: "exponential" }, timeout: "60 seconds" },
            async () => hubspotUpsert({}),
        );

        // ─── Wave 5 ───
        const hubspot_create_list_result = await step.do(
            "hubspot_create_list",
            { retries: { limit: 5, delay: "5 seconds", backoff: "exponential" }, timeout: "10 minutes" },
            async () => hubspotCreateList({}),
        );

        // ─── Wave 6 ───
        const exclusion_check_dnc_result = await step.do(
            "exclusion_check_dnc",
            { timeout: "10 minutes" },
            async () => exclusionCheckDnc({}),
        );

        // ─── Wave 7 ───
        const exclusion_check_recent_result = await step.do(
            "exclusion_check_recent",
            { timeout: "10 minutes" },
            async () => exclusionCheckRecent({}),
        );

        // ─── Wave 8 ───
        const exclusion_check_sequence_result = await step.do(
            "exclusion_check_sequence",
            { timeout: "10 minutes" },
            async () => exclusionCheckSequence({}),
        );

        // ─── Wave 9 ───
        const personalize_email_result = await step.do(
            "personalize_email",
            { timeout: "10 minutes" },
            async () => personalizeEmail({}, this.env),
        );

        // ─── Wave 10 ───
        const create_sales_template_result = await step.do(
            "create_sales_template",
            { retries: { limit: 3, delay: "5 seconds", backoff: "exponential" }, timeout: "10 minutes" },
            async () => createSalesTemplate({}),
        );

        // ─── Wave 11 ───
        const pre_enrollment_report_result = await step.do(
            "pre_enrollment_report",
            { timeout: "10 minutes" },
            async () => preEnrollmentReport({}),
        );

        // ─── Wave 12 ───
        // ─── HITL gate: manual_enrollment_handoff ───
        // Workflow suspends here until an event of type 'bdr_enrollment_complete'
        // arrives. Survives hibernation; events that arrive before this
        // line is reached are buffered and delivered when reached.
        const manual_enrollment_handoff_event = await step.waitForEvent<any>(
            "manual_enrollment_handoff",
            { type: "bdr_enrollment_complete", timeout: "14 days" },
        );
        const manual_enrollment_handoff_result = manual_enrollment_handoff_event.payload;

        return {
            "manual_enrollment_handoff": manual_enrollment_handoff_result as Record<string, unknown>,
        };
    }
}
