        /**
         * Auto-generated by rote.adapters.cloudflare.
         *
         * Pipeline: bdr-campaign v0.1.0
         * Source skill: ../skill
         * Pipeline hash: ada0f771
         *
         * DO NOT EDIT BY HAND. Re-run `rote emit --runtime cloudflare` to regenerate.
         *
         * Architecture note: every external_call step in this workflow wraps a
         * deterministic API call from the `extracted/` modules. None of them call
         * MCP tools at runtime — those calls were compiled into direct API calls
         * during the rote emission step.
         */

        import {
            WorkflowEntrypoint,
            WorkflowEvent,
            WorkflowStep,
        } from "cloudflare:workers";
import { NonRetryableError } from "cloudflare:workflows";

import { targetResearch } from "./extracted/target_research";
import { taxonomyLookup } from "./extracted/taxonomy_lookup";
import { leadGenerationLoop } from "./extracted/lead_generation_loop";
import { enrichContactBatch } from "./extracted/enrich_contact_batch";
import { vetContact } from "./signatures/vet_contact";
import { hubspotUpsert } from "./extracted/hubspot_upsert";
import { hubspotCreateList } from "./extracted/hubspot_create_list";
import { exclusionCheckDnc } from "./extracted/exclusion_check_dnc";
import { exclusionCheckRecent } from "./extracted/exclusion_check_recent";
import { exclusionCheckSequence } from "./extracted/exclusion_check_sequence";
import { personalizeEmail } from "./signatures/personalize_email";
import { createSalesTemplate } from "./extracted/create_sales_template";
import { preEnrollmentReport } from "./extracted/pre_enrollment_report";
import { isRoteMcpAuthNeeded } from "./extracted/_roteMcp";

export interface Env {
    ANTHROPIC_API_KEY: string;
    AI?: Ai;
    PIPELINE: Workflow<Params>;
}

export type Params = Record<string, unknown>;

/** A failed step's error carries the auth signal. Cloudflare serializes
 * step errors across hibernation/replay — class identity is lost, so
 * detection is by `name` with the message text as fallback. */
function stepNeedsAuth(err: unknown): boolean {
    if (isRoteMcpAuthNeeded(err)) return true;
    const msg = err instanceof Error ? err.message : String(err);
    return msg.includes("needs (re)authentication");
}

/** Which server's release event unparks this failure.
 *
 * A step bound to one MCP server knows its event at emit time; an agent
 * loop may reach several (and ROTE_MCP_SERVERS can add more at run time),
 * so the server is read back off the error. The name survives the
 * NonRetryableError re-throw because RoteMcpAuthNeeded puts it in the
 * message — own properties do not reliably cross a step boundary. */
function authEventType(err: unknown, fallback: string): string {
    const direct = (err as { server?: unknown })?.server;
    if (typeof direct === "string" && direct.length > 0) return `rote_auth_${direct}`;
    const msg = err instanceof Error ? err.message : String(err);
    const match = /MCP server '([A-Za-z0-9_-]+)'/.exec(msg);
    return match ? `rote_auth_${match[1]}` : fallback;
}

/** The list a fan_out node dispatches over.
 *
 * A bare `.map()` on a missing key fails with "Cannot read properties
 * of undefined (reading 'map')", which names neither the node nor the
 * reference — in generated code that is close to undebuggable, and the
 * cause is almost always an upstream node that didn't return the key
 * the IR says it does. One call turns that into an actionable message.
 * Found by running it: the first live fan_out run hit exactly this. */
function fanOutList(value: unknown, nodeId: string, ref: string): unknown[] {
    if (!Array.isArray(value)) {
        const got = value === null ? "null" : typeof value;
        throw new Error(
            `fan_out node '${nodeId}' expected an array from '${ref}', got ${got}. ` +
                `The upstream node must return that key as a list.`,
        );
    }
    return value;
}

export class BdrCampaignWorkflow extends WorkflowEntrypoint<Env, Params> {
    async run(event: WorkflowEvent<Params>, step: WorkflowStep) {
        const pipelineInput = event.payload;

        // ─── Wave 1 ───
        const taxonomy_lookup_result = await step.do(
            "taxonomy_lookup",
            { timeout: "10 minutes" },
            async () => taxonomyLookup({
                brief: pipelineInput,
            }),
        );
        // ─── target_research (agent loop): park on dead credentials ───
        // Agent loop: the parked server names itself in the auth error,
        // so `rote mcp release <server>` releases the right instances.
        let target_research_result!: Record<string, unknown>;
        for (let target_research_attempt = 0; ; target_research_attempt++) {
            try {
                target_research_result = (await step.do(
                    target_research_attempt === 0
                        ? "target_research"
                        : `target_research (auth retry ${target_research_attempt})`,
                    { retries: { limit: 2, delay: "5 seconds", backoff: "exponential" }, timeout: "5 minutes" },
                    async () => {
                        try {
                            return await targetResearch({
                            brief: pipelineInput,
                        }, this.env);
                        } catch (err) {
                            // No retry mints a credential — skip the budget.
                            throw isRoteMcpAuthNeeded(err)
                                ? new NonRetryableError(
                                      err instanceof Error ? err.message : String(err),
                                  )
                                : err;
                        }
                    },
                )) as Record<string, unknown>;
                break;
            } catch (err) {
                if (!stepNeedsAuth(err)) throw err;
                // Retry once immediately (another isolate may have
                // refreshed the KV token cache); park on the second
                // consecutive failure. Fresh step names per attempt.
                if (target_research_attempt % 2 === 1) {
                    await step.waitForEvent<any>(
                        `target_research auth wait ${target_research_attempt}`,
                        { type: authEventType(err, "rote_auth_airweave"), timeout: "30 days" },
                    );
                }
            }
        }

        // ─── Wave 2 ───
        // ─── lead_generation_loop (agent loop): park on dead credentials ───
        // Agent loop: the parked server names itself in the auth error,
        // so `rote mcp release <server>` releases the right instances.
        let lead_generation_loop_result!: Record<string, unknown>;
        for (let lead_generation_loop_attempt = 0; ; lead_generation_loop_attempt++) {
            try {
                lead_generation_loop_result = (await step.do(
                    lead_generation_loop_attempt === 0
                        ? "lead_generation_loop"
                        : `lead_generation_loop (auth retry ${lead_generation_loop_attempt})`,
                    { timeout: "15 minutes" },
                    async () => {
                        try {
                            return await leadGenerationLoop({
                            brief: pipelineInput,
                            intel: target_research_result,
                            taxonomy: taxonomy_lookup_result,
                            target_quota: pipelineInput["target_quota"],
                        }, this.env);
                        } catch (err) {
                            // No retry mints a credential — skip the budget.
                            throw isRoteMcpAuthNeeded(err)
                                ? new NonRetryableError(
                                      err instanceof Error ? err.message : String(err),
                                  )
                                : err;
                        }
                    },
                )) as Record<string, unknown>;
                break;
            } catch (err) {
                if (!stepNeedsAuth(err)) throw err;
                // Retry once immediately (another isolate may have
                // refreshed the KV token cache); park on the second
                // consecutive failure. Fresh step names per attempt.
                if (lead_generation_loop_attempt % 2 === 1) {
                    await step.waitForEvent<any>(
                        `lead_generation_loop auth wait ${lead_generation_loop_attempt}`,
                        { type: authEventType(err, "rote_auth_airweave"), timeout: "30 days" },
                    );
                }
            }
        }

        // ─── Wave 3 ───
        // ─── HITL gate: contact_review_gate ───
        // Workflow suspends here until an event of type 'contact_review_approved'
        // arrives. Survives hibernation; events that arrive before this
        // line is reached are buffered and delivered when reached.
        const contact_review_gate_event = await step.waitForEvent<any>(
            "contact_review_gate",
            { type: "contact_review_approved", timeout: "7 days" },
        );
        const contact_review_gate_result = contact_review_gate_event.payload;

        // ─── Wave 4 ───
        const hubspot_upsert_result = await step.do(
            "hubspot_upsert",
            { retries: { limit: 5, delay: "5 seconds", backoff: "exponential" }, timeout: "60 seconds" },
            async () => hubspotUpsert({
                contacts: (contact_review_gate_result as Record<string, unknown>)["approved_contacts"],
            }),
        );

        // ─── Wave 5 ───
        const hubspot_create_list_result = await step.do(
            "hubspot_create_list",
            { retries: { limit: 5, delay: "5 seconds", backoff: "exponential" }, timeout: "10 minutes" },
            async () => hubspotCreateList({
                campaign_name: pipelineInput["drug_brand"],
                contacts: (hubspot_upsert_result as Record<string, unknown>)["upserted"],
            }),
        );

        // ─── Wave 6 ───
        const exclusion_check_dnc_result = await step.do(
            "exclusion_check_dnc",
            { timeout: "10 minutes" },
            async () => exclusionCheckDnc({
                contacts: (hubspot_upsert_result as Record<string, unknown>)["upserted"],
            }),
        );

        // ─── Wave 7 ───
        const exclusion_check_recent_result = await step.do(
            "exclusion_check_recent",
            { timeout: "10 minutes" },
            async () => exclusionCheckRecent({
                contacts: (exclusion_check_dnc_result as Record<string, unknown>)["passed"],
            }),
        );

        // ─── Wave 8 ───
        const exclusion_check_sequence_result = await step.do(
            "exclusion_check_sequence",
            { timeout: "10 minutes" },
            async () => exclusionCheckSequence({
                contacts: (exclusion_check_recent_result as Record<string, unknown>)["passed"],
            }),
        );

        // ─── Wave 9 ───
        // fan_out: personalize_email runs once per element of the bound list,
        // each as its own durable step (names are index-suffixed —
        // Cloudflare caches step results by name).
        const personalize_email_result = await Promise.all(
            fanOutList(
                (exclusion_check_sequence_result as Record<string, unknown>)["passed"],
                "personalize_email",
                "exclusion_check_sequence.output.passed",
            ).map((_item, _index) =>
                step.do(
                    `personalize_email[${_index}]`,
                    { timeout: "10 minutes" },
                    async () => personalizeEmail({ contact: _item, intel: target_research_result, campaign_type: pipelineInput["campaign_type"] }, this.env),
                ),
            ),
        );

        // ─── Wave 10 ───
        const create_sales_template_result = await step.do(
            "create_sales_template",
            { retries: { limit: 3, delay: "5 seconds", backoff: "exponential" }, timeout: "10 minutes" },
            async () => createSalesTemplate({
                campaign_name: pipelineInput["drug_brand"],
                personalizations: personalize_email_result,
            }),
        );

        // ─── Wave 11 ───
        const pre_enrollment_report_result = await step.do(
            "pre_enrollment_report",
            { timeout: "10 minutes" },
            async () => preEnrollmentReport({
                campaign_name: pipelineInput["drug_brand"],
                passed_contacts: (exclusion_check_sequence_result as Record<string, unknown>)["passed"],
                exclusions: (exclusion_check_sequence_result as Record<string, unknown>)["excluded"],
                template_ids: (create_sales_template_result as Record<string, unknown>)["template_ids"],
            }),
        );

        // ─── Wave 12 ───
        // ─── HITL gate: manual_enrollment_handoff ───
        // Workflow suspends here until an event of type 'bdr_enrollment_complete'
        // arrives. Survives hibernation; events that arrive before this
        // line is reached are buffered and delivered when reached.
        const manual_enrollment_handoff_event = await step.waitForEvent<any>(
            "manual_enrollment_handoff",
            { type: "bdr_enrollment_complete", timeout: "14 days" },
        );
        const manual_enrollment_handoff_result = manual_enrollment_handoff_event.payload;

        return {
            "manual_enrollment_handoff": manual_enrollment_handoff_result as Record<string, unknown>,
        };
    }
}
