/**
 * Type contracts for the static before/after scorecard.
 *
 * These mirror `rote.eval.scorecard.Scorecard.to_dict()` in the OSS
 * Python exactly: rote-cloud stores that JSON verbatim in its `pipelines`
 * table and serves it to the console unchanged, so the TS shape here is
 * the single source of truth both sides validate against. Types only —
 * no runtime code — because nothing in TS produces a scorecard; it is
 * always generated by the Python estimator and consumed here.
 */

/** An inclusive [low, high] estimate. Exact values have low === high. */
export interface Range {
  low: number;
  high: number;
}

/** Node kinds a graduated step can be (rote IR `NodeKind`). */
export type NodeKind =
  | "pure_function"
  | "llm_judge"
  | "agent_loop"
  | "hitl_gate"
  | "external_call";

/** Relative capability tier within a provider's lineup (`ModelTier`). */
export type ModelTier = "flagship" | "mid" | "small";

/** One node's per-run footprint, as emitted under `after.nodes[]`. */
export interface ScorecardNode {
  id: string;
  kind: NodeKind;
  calls: Range;
  llm_input_tokens_per_call: number;
  llm_output_tokens_per_call: number;
  wall_seconds_per_call: number;
  /** Present only when the node carries a modeling assumption worth
   *  surfacing (the Python omits the key otherwise). */
  note?: string;
}

/** The "before" block: the skill run as raw agent instructions. Null when
 *  no skill baseline was supplied to the estimator. */
export interface ScorecardBefore {
  turns: Range;
  context_tokens: number;
  fresh_input_tokens: Range;
  cached_read_tokens: Range;
  output_tokens: Range;
  wall_seconds: Range;
  sampled_steps: number;
  total_steps: number;
  sampled_output_tokens: Range;
  turn_method: string;
  token_count_method: string;
}

/** The "after" block: the graduated pipeline. */
export interface ScorecardAfter {
  critical_path_seconds: Range;
  hitl_gates: string[];
  llm_input_tokens: Range;
  llm_output_tokens: Range;
  sampled_steps: number;
  total_steps: number;
  schema_constrained_steps: number;
  sampled_output_tokens: Range;
  nodes: ScorecardNode[];
}

/** One model priced against both estimates. */
export interface CostRow {
  model: string;
  provider: string;
  tier: ModelTier;
  price_source: string;
  fetched_at: string;
  input_per_mtok: number;
  output_per_mtok: number;
  /** Null when there is no skill baseline to price. */
  before_usd: Range | null;
  after_usd: Range;
}

/**
 * The calibratable estimator priors (`rote.eval.priors.Priors`), emitted
 * via `asdict`. `tokens_per_external_call_result` and
 * `payload_tokens_per_tool` are optional because they were added to
 * Priors after early scorecards were generated — older stored scorecards
 * (and the demo fixture) omit them, and the contract must accept both.
 */
export interface ScorecardPriors {
  seconds_per_turn: number;
  output_tokens_per_turn: number;
  transcript_growth_per_turn: number;
  system_overhead_tokens: number;
  tokens_per_external_call_result?: number;
  payload_tokens_per_tool?: Record<string, number>;
  turns_per_step_low: number;
  turns_per_step_high: number;
  llm_ttft_seconds: number;
  llm_output_tokens_per_second: number;
  tokens_per_input_field: number;
  tokens_per_output_field: number;
  external_call_seconds: number;
  pure_function_seconds: number;
  agent_loop_turns_per_iteration: number;
  agent_loop_default_max_iterations: number;
  chars_per_token: number;
}

/** The full scorecard JSON, as `Scorecard.to_dict()` produces it. */
export interface Scorecard {
  pipeline: string;
  generated_at: string;
  /** Share of pipeline steps that run as deterministic routine (code)
   *  rather than LLM inference; 0.0 = pure agent, 1.0 = pure code. */
  roteness: number;
  /** Null when the estimator was given no skill baseline. */
  before: ScorecardBefore | null;
  after: ScorecardAfter;
  costs: CostRow[];
  priors: ScorecardPriors;
}
