"""Typed LLM signature: identify_steps

Read the full skill bundle and identify every distinct pipeline step.

Auto-generated by rote.adapters.dbos from the IR's ``signature_spec``.
The non-determinism lives inside this module; the workflow step that
calls it stays a checkpointed, retryable unit.

DO NOT EDIT BY HAND. Re-run ``rote emit --runtime dbos`` to regenerate.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any

from pydantic import BaseModel, ConfigDict


class IdentifyStepsInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    skill_md: str
    reference_files: dict[str, Any]


class StepDescription(BaseModel):
    model_config = ConfigDict(extra="forbid")

    step_id: str
    name: str
    description: str
    source_section: str
    phase: str | None = None


class IdentifyStepsOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    steps: list[StepDescription]


PROMPT = (
    "You are analyzing a skill bundle to identify all distinct pipeline steps.\n\nA \"ste"
    "p\" is a unit of work that could become one IR node. Each step\nshould have one clea"
    "r input type and one clear output type, and map\nto one SKILL.md section or heading."
    " Do not merge steps that are\nlogically separate, even if the prose describes them a"
    "djacently.\n\nIdentify every phase, gate, data pull, transformation, and output\nste"
    "p. Err toward more granular \u2014 it is better to have more steps\nthan to under-de"
    "compose.\n\nGive each step a snake_case step_id that will become its IR node id.\nA "
    "node id must match [a-z][a-z0-9_]* and be unique within this skill.\n\nSKILL.md:\n{{"
    " skill_md }}\n\nReference files:\n{{ reference_files }}\n\nReturn all identified ste"
    "ps via the structured output tool.\n"
)

TOOL_DESCRIPTION = "Read the full skill bundle and identify every distinct pipeline step."

OUTPUT_JSON_SCHEMA: dict[str, Any] = json.loads(
    "{\"type\":\"object\",\"title\":\"IdentifyStepsOutput\",\"additionalProperties\":fals"
    "e,\"properties\":{\"steps\":{\"type\":\"array\",\"description\":\"All distinct steps"
    " in execution order\",\"items\":{\"$ref\":\"#/$defs/StepDescription\"}}},\"required\""
    ":[\"steps\"],\"$defs\":{\"StepDescription\":{\"type\":\"object\",\"additionalPropert"
    "ies\":false,\"properties\":{\"step_id\":{\"type\":\"string\",\"description\":\"snake"
    "_case identifier; will become node id\"},\"name\":{\"type\":\"string\",\"description"
    "\":\"Human-readable step name\"},\"description\":{\"type\":\"string\",\"description\""
    ":\"What the step does, 1-2 sentences\"},\"source_section\":{\"type\":\"string\",\"de"
    "scription\":\"Exact SKILL.md heading text (without # markers)\"},\"phase\":{\"anyOf\""
    ":[{\"type\":\"string\"},{\"type\":\"null\"}],\"default\":null,\"description\":\"Skil"
    "l phase number or name\"}},\"required\":[\"step_id\",\"name\",\"description\",\"sour"
    "ce_section\"]}}}"
)

# Operator overrides: change the model or point at a different
# endpoint (proxy, gateway, OpenAI-compatible server) without
# re-emitting. Unset means the default below / the vendor's endpoint.
MODEL = os.environ.get("ROTE_MODEL_IDENTIFY_STEPS", "claude-sonnet-4-6")
BASE_URL = os.environ.get("ROTE_BASE_URL_IDENTIFY_STEPS")


def _interpolate(template: str, variables: dict[str, Any]) -> str:
    """Resolve ``{{ dotted.path }}`` placeholders against the input dict.

    An unresolvable placeholder raises instead of interpolating "" —
    a hole in a judge prompt produces confident garbage that is far
    harder to debug than a KeyError naming the missing variable.
    """

    def _resolve(match: re.Match[str]) -> str:
        path = match.group(1)
        value: Any = variables
        for part in path.split("."):
            if not isinstance(value, dict) or part not in value:
                raise KeyError(
                    f"prompt template references {{{{ {path} }}}} but the "
                    f"input has no such field; available top-level keys: "
                    f"{sorted(variables)}"
                )
            value = value[part]
        if value is None:
            return ""
        return value if isinstance(value, str) else json.dumps(value, default=str)

    return re.sub(r"\{\{\s*([\w.]+)\s*\}\}", _resolve, template)


class IdentifySteps:
    """Typed LLM judge for identify_steps (Anthropic structured output)."""

    def forward(self, inputs: IdentifyStepsInput) -> IdentifyStepsOutput:
        # Which provider serves this call — and who is billed for it —
        # is resolved at runtime; see signatures/_rote_inference.py.
        from signatures._rote_inference import call_judge

        payload = call_judge(
            node_id="identify_steps",
            client="anthropic",
            model=MODEL,
            base_url=BASE_URL,
            prompt=_interpolate(PROMPT, inputs.model_dump(by_alias=True)),
            output_schema=OUTPUT_JSON_SCHEMA,
            tool_description=TOOL_DESCRIPTION,
        )
        return IdentifyStepsOutput.model_validate(payload)
