"""LLM signature: personalize a single outreach email.

# Source rubric

The bdr-outreach skill's ``references/email-templates.md`` defines a
fixed email template with two variable slots:

* **Opening line** — a specific observation about the contact's work
  (drawn from their employment history and the campaign intel brief).
* **TA callout** — a TA-specific reference grounded in Acme's
  validated experience in the indication.

The body of the email is templated and not generated by the LLM. The
LLM only fills these two slots, which keeps the per-contact token cost
low and makes the output trivially evaluable.

# Graduated form

Like ``vet_contact``, this is a typed LLM signature with a bounded
output schema. Fan-out is configured at the IR level
(``fan_out: true``) so the Temporal workflow invokes one activity per
contact in parallel.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from ..types import (
    CampaignType,
    IntelBrief,
    VettedContact,
)


class PersonalizeEmailInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    contact: VettedContact
    intel: IntelBrief
    campaign_type: CampaignType


class PersonalizeEmailOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    opening_line: str
    ta_callout: str


class PersonalizeEmail:
    """Typed LLM judge for BDR email personalization."""

    async def forward(
        self, inputs: PersonalizeEmailInput
    ) -> PersonalizeEmailOutput:
        """Generate the per-contact opening line and TA callout."""
        raise NotImplementedError(
            "PersonalizeEmail.forward: implement against an LLM signature framework"
        )
