/**
 * MCP connection helper for Cloudflare Workers (generated by rote — do
 * not edit; the source of truth is
 * rote.adapters._ts_common.ROTE_MCP_WORKERS_HELPER_TS).
 *
 * Credentials come from Worker secrets provisioned by
 * `rote mcp export <server>` (see README):
 *   ROTE_MCP_<SERVER>_REFRESH_TOKEN / _CLIENT_ID / _CLIENT_SECRET? /
 *   _TOKEN_ENDPOINT / _URL?
 * Access tokens are minted at runtime via the OAuth refresh grant and
 * cached — with rotated refresh tokens — in the ROTE_MCP_TOKENS KV
 * namespace, so every isolate sees the latest credentials.
 */

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import {
    StreamableHTTPClientTransport,
    StreamableHTTPError,
} from "@modelcontextprotocol/sdk/client/streamableHttp.js";

export interface RoteMcpEnv {
    ROTE_MCP_TOKENS?: KVNamespace;
    [key: string]: unknown;
}

/**
 * The MCP server needs re-provisioned credentials (Workers cannot run an
 * interactive login — the fix is `rote mcp login` + `rote mcp export` +
 * re-uploading the secrets). Detect with isRoteMcpAuthNeeded(), never
 * `instanceof`: Workflows serialize errors across hibernation and replay
 * boundaries — class identity is lost, `name` survives.
 */
export class RoteMcpAuthNeeded extends Error {
    readonly server: string;
    readonly reason: string;

    constructor(server: string, reason: string) {
        super(
            `MCP server '${server}' needs (re)authentication — ${reason}. ` +
                `Re-provision with: rote mcp login ${server} && rote mcp export ${server}`,
        );
        this.name = "RoteMcpAuthNeeded";
        this.server = server;
        this.reason = reason;
    }
}

/** True if a RoteMcpAuthNeeded hides anywhere in the error tree. */
export function isRoteMcpAuthNeeded(err: unknown): boolean {
    let node: unknown = err;
    for (let depth = 0; node != null && depth < 16; depth++) {
        const e = node as { name?: unknown; errors?: unknown; cause?: unknown };
        if (e.name === "RoteMcpAuthNeeded") return true;
        if (Array.isArray(e.errors) && e.errors.some((sub) => isRoteMcpAuthNeeded(sub))) {
            return true;
        }
        node = e.cause;
    }
    return false;
}

// Concrete JSON types: Cloudflare's step.do constrains callback returns to
// Rpc.Serializable, which `unknown` members do not satisfy — a recursive
// concrete JSON shape does (same reason emitted stubs are Promise<never>).
export type JsonValue = string | number | boolean | null | JsonValue[] | JsonObject;
export type JsonObject = { [key: string]: JsonValue };

interface TokenState {
    access_token: string;
    expires_at: number | null;
    refresh_token?: string;
}

/** Per-isolate fallback cache when no KV binding is configured. */
const memoryCache = new Map<string, TokenState>();

function secret(env: RoteMcpEnv, server: string, suffix: string): string | undefined {
    const value = env[`ROTE_MCP_${server.toUpperCase()}_${suffix}`];
    return typeof value === "string" && value.length > 0 ? value : undefined;
}

export function resolveUrl(
    env: RoteMcpEnv,
    server: string,
    pipelineUrl: string | null,
): string {
    const bound = secret(env, server, "URL") ?? pipelineUrl;
    if (bound) return bound;
    throw new Error(
        `no endpoint for MCP server '${server}' — set the ` +
            `ROTE_MCP_${server.toUpperCase()}_URL variable (wrangler.jsonc vars or secret)`,
    );
}

async function readState(env: RoteMcpEnv, server: string): Promise<TokenState | null> {
    if (env.ROTE_MCP_TOKENS) {
        return (await env.ROTE_MCP_TOKENS.get(`mcp-token:${server}`, "json")) as
            | TokenState
            | null;
    }
    return memoryCache.get(server) ?? null;
}

async function writeState(env: RoteMcpEnv, server: string, state: TokenState): Promise<void> {
    if (env.ROTE_MCP_TOKENS) {
        await env.ROTE_MCP_TOKENS.put(`mcp-token:${server}`, JSON.stringify(state));
    } else {
        memoryCache.set(server, state);
    }
}

async function refreshAccessToken(env: RoteMcpEnv, server: string): Promise<string> {
    const state = await readState(env, server);
    // A rotated refresh token in KV supersedes the provisioned secret.
    const refreshToken = state?.refresh_token ?? secret(env, server, "REFRESH_TOKEN");
    const tokenEndpoint = secret(env, server, "TOKEN_ENDPOINT");
    const clientId = secret(env, server, "CLIENT_ID");
    const upper = server.toUpperCase();
    if (!refreshToken || !tokenEndpoint || !clientId) {
        throw new RoteMcpAuthNeeded(
            server,
            `the ROTE_MCP_${upper}_* secrets are not provisioned (wrangler secret bulk)`,
        );
    }
    const body = new URLSearchParams({
        grant_type: "refresh_token",
        refresh_token: refreshToken,
        client_id: clientId,
    });
    const clientSecret = secret(env, server, "CLIENT_SECRET");
    if (clientSecret) body.set("client_secret", clientSecret);
    const response = await fetch(tokenEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: body.toString(),
    });
    if (!response.ok) {
        throw new RoteMcpAuthNeeded(
            server,
            `the refresh grant failed (${response.status}) — the provisioned ` +
                `refresh token may be revoked`,
        );
    }
    const granted = (await response.json()) as {
        access_token: string;
        expires_in?: number;
        refresh_token?: string;
    };
    await writeState(env, server, {
        access_token: granted.access_token,
        expires_at:
            granted.expires_in != null ? Date.now() / 1000 + granted.expires_in : null,
        // Persist rotation — losing a rotated refresh token strands the Worker.
        refresh_token: granted.refresh_token ?? refreshToken,
    });
    return granted.access_token;
}

async function accessToken(
    env: RoteMcpEnv,
    server: string,
    forceRefresh: boolean,
): Promise<string> {
    if (!forceRefresh) {
        const state = await readState(env, server);
        if (
            state?.access_token &&
            (state.expires_at == null || Date.now() / 1000 < state.expires_at - 60)
        ) {
            return state.access_token;
        }
    }
    return refreshAccessToken(env, server);
}

/**
 * Run `fn` against a connected, authenticated MCP session.
 *
 * Every operation shares one auth story: try with the cached token, and
 * on a 401 refresh once and retry on a fresh transport. Anything a
 * refresh cannot fix becomes RoteMcpAuthNeeded so the instance parks.
 */
async function withMcpSession<T>(
    env: RoteMcpEnv,
    server: string,
    pipelineUrl: string | null,
    fn: (client: Client) => Promise<T>,
): Promise<T> {
    const url = resolveUrl(env, server, pipelineUrl);

    const attempt = async (token: string) => {
        const client = new Client({ name: "rote-pipeline", version: "1.0.0" });
        const transport = new StreamableHTTPClientTransport(new URL(url), {
            requestInit: { headers: { Authorization: `Bearer ${token}` } },
        });
        try {
            await client.connect(transport);
            return await fn(client);
        } finally {
            await client.close().catch(() => undefined);
        }
    };

    try {
        return await attempt(await accessToken(env, server, false));
    } catch (err) {
        if (!isUnauthorizedWorkers(err)) throw err;
        try {
            return await attempt(await accessToken(env, server, true));
        } catch (retryErr) {
            if (isUnauthorizedWorkers(retryErr)) {
                throw new RoteMcpAuthNeeded(
                    server,
                    "the server returned 401 even after a token refresh",
                );
            }
            throw retryErr;
        }
    }
}

/**
 * Call one tool on an MCP server, authenticated from provisioned Worker
 * secrets + KV-cached tokens. Retries once with a forced refresh on 401.
 */
export async function callMcpTool(
    env: RoteMcpEnv,
    server: string,
    pipelineUrl: string | null,
    tool: string,
    args: Record<string, unknown>,
): Promise<JsonObject> {
    return withMcpSession(env, server, pipelineUrl, async (client) => {
        const result = await client.callTool({ name: tool, arguments: args });
        if (result.isError) {
            throw new Error(
                `MCP tool '${tool}' on '${server}' returned an error: ` +
                    JSON.stringify(result.content),
            );
        }
        if (result.structuredContent) {
            return result.structuredContent as JsonObject;
        }
        const text = (result.content as Array<{ type: string; text?: string }>).find(
            (block) => block.type === "text",
        )?.text;
        return (text ? JSON.parse(text) : {}) as JsonObject;
    });
}

/** One tool as the server advertises it. */
export interface McpToolSpec {
    name: string;
    description: string;
    inputSchema: Record<string, unknown>;
}

/**
 * Every tool `server` advertises, with the JSON Schema it declares.
 *
 * An agent_loop names bare tools; the schema the model needs to call one
 * correctly lives on the server, not in the IR. Fetching it here means
 * the agent's tool contract is always the server's current contract —
 * it cannot go stale the way a schema copied into the pipeline would.
 */
export async function listMcpTools(
    env: RoteMcpEnv,
    server: string,
    pipelineUrl: string | null,
): Promise<McpToolSpec[]> {
    return withMcpSession(env, server, pipelineUrl, async (client) => {
        const { tools } = await client.listTools();
        return tools.map((tool) => ({
            name: tool.name,
            description: tool.description ?? "",
            inputSchema: (tool.inputSchema ?? {
                type: "object",
                properties: {},
            }) as Record<string, unknown>,
        }));
    });
}

/** A tool bound to a callable — structurally a BoundTool for the agent loop. */
export interface BoundMcpTool {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
    run: (args: Record<string, unknown>) => Promise<JsonObject>;
}

/**
 * Candidate servers for tool discovery.
 *
 * Unlike the Node runtimes there is no registry file to enumerate here —
 * a Worker's servers are whatever the pipeline declared at emit time,
 * with their credentials provisioned as secrets under those names. The
 * ROTE_MCP_SERVERS variable replaces the list wholesale when an operator
 * needs to point a loop somewhere the pipeline never mentioned.
 */
function agentServerNames(env: RoteMcpEnv, declared: string[]): string[] {
    const override = env.ROTE_MCP_SERVERS;
    if (typeof override === "string" && override.length > 0) {
        return override
            .split(",")
            .map((name) => name.trim())
            .filter(Boolean);
    }
    return [...new Set(declared)].sort();
}

/**
 * Bind the tools an agent_loop declared to callables the loop can invoke.
 *
 * Same contract as the Node helper's: discovery is best-effort per server
 * (a server that is down may not be one this loop needed), a declared tool
 * no reachable server provides is fatal, and an auth failure that plausibly
 * explains the gap is rethrown so the Workflow parks on it instead of
 * failing with a misleading "no server provides this tool".
 */
export async function bindAgentTools(
    env: RoteMcpEnv,
    allowed: string[],
    declaredServers: string[],
    serverUrls: Record<string, string | null> = {},
    toolServers: Record<string, string> = {},
): Promise<BoundMcpTool[]> {
    const wanted = new Set(allowed);
    const bound = new Map<string, BoundMcpTool>();
    const failures: unknown[] = [];

    for (const server of agentServerNames(env, declaredServers)) {
        const url = serverUrls[server] ?? null;
        let specs: McpToolSpec[];
        try {
            specs = await listMcpTools(env, server, url);
        } catch (err) {
            failures.push(err);
            continue;
        }
        for (const spec of specs) {
            if (!wanted.has(spec.name) || bound.has(spec.name)) continue;
            // Resolved tools bind only from their own server — see the
            // Node helper's twin for why first-wins is not good enough.
            const pinned = toolServers[spec.name];
            if (pinned !== undefined && pinned !== server) continue;
            bound.set(spec.name, {
                name: spec.name,
                description: spec.description,
                parameters: spec.inputSchema,
                run: (args) => callMcpTool(env, server, url, spec.name, args),
            });
        }
    }

    const missing = allowed.filter((name) => !bound.has(name));
    if (missing.length > 0) {
        const authFailure = failures.find((err) => isRoteMcpAuthNeeded(err));
        if (authFailure) throw authFailure;
        const detail = failures
            .map((err) => (err instanceof Error ? err.message : String(err)))
            .join("; ");
        throw new Error(
            `agent tools not provided by any reachable MCP server: ${missing.join(", ")}` +
                (detail ? ` (unreachable: ${detail})` : ""),
        );
    }
    return [...bound.values()];
}

function isUnauthorizedWorkers(err: unknown): boolean {
    return err instanceof StreamableHTTPError
        ? err.code === 401
        : /\b401\b|[Uu]nauthorized/.test(String(err));
}
