/**
 * Agent loop: target_research
 *
 * Run external research (Bright Data web search, ClinicalTrials.gov)
 *
 * Auto-generated by rote.adapters.cloudflare. Bounded at 10 iteration(s)
 * and restricted to the tools below — the agent sees nothing else. Which
 * lane pays for the inference (your Anthropic key, your Cloudflare account,
 * or rote cloud) is resolved at runtime by signatures/_roteInference.ts;
 * ROTE_MODEL_TARGET_RESEARCH / ROTE_BASE_URL_TARGET_RESEARCH override the model and endpoint.
 */

import { runAgentLoop, type BoundTool, type WorkersAiLane } from "../signatures/_roteInference";
import { bindAgentTools, type RoteMcpEnv } from "./_roteMcp";
import { runWithTools } from "@cloudflare/ai-utils";

/** Tools the IR declared for this loop — the allowlist IS the boundary. */
const TOOLS: string[] = ["bright_data_search", "bright_data_scrape", "clinical_trials_search", "airweave_search", "salesforce_query"];

// NOTE: no MCP server could be resolved at emit time — this loop's
// tools are bare names and no node in the pipeline carries an `mcp:`
// binding to search. The Node runtimes fall back to every server in
// the local rote registry; set ROTE_MCP_SERVERS to name them
// explicitly (required on Cloudflare, which has no registry).
/** Servers searched for those tools, with the endpoints the IR recorded. */
const SERVERS: string[] = [];
const SERVER_URLS: Record<string, string | null> = {};

export async function targetResearch(
    input: unknown,
    env: unknown, // the workflow's Env; cast below
): Promise<{ result: string; provider: string; iterations: number | null }> {
    const vars = env as Record<string, string | undefined>;
    const tools: BoundTool[] = await bindAgentTools(env as RoteMcpEnv, TOOLS, SERVERS, SERVER_URLS);
    const ai = (env as { AI?: unknown }).AI;
    const workersAi: WorkersAiLane | null = ai
        ? {
              binding: ai,
              model: vars.ROTE_WORKERS_AI_MODEL ?? "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
              runWithTools: runWithTools as WorkersAiLane["runWithTools"],
          }
        : null;
    return runAgentLoop({
        nodeId: "target_research",
        description: "Run external research (Bright Data web search, ClinicalTrials.gov)\nand internal research (Airweave enterprise search, Salesforce account\nhistory, internal publications) in parallel. Compile a short intel\nbrief covering pipeline, RWE/HEOR signals, key programs/teams, prior\naccount interactions, and validated TA experience.\n",
        task: input,
        model: vars.ROTE_MODEL_TARGET_RESEARCH ?? "claude-sonnet-4-6",
        tools,
        maxIterations: 10,
        baseUrl: vars.ROTE_BASE_URL_TARGET_RESEARCH ?? null,
        env: vars,
        workersAi,
    });
}
