/**
 * Agent loop: target_research
 *
 * Run external research (Bright Data web search, ClinicalTrials.gov)
 *
 * Auto-generated by rote.adapters.cloudflare. Bounded at 10 iteration(s)
 * and restricted to the tools below — the agent sees nothing else. Which
 * lane pays for the inference (your Anthropic key, your Cloudflare account,
 * or rote cloud) is resolved at runtime by signatures/_roteInference.ts;
 * ROTE_MODEL_TARGET_RESEARCH / ROTE_BASE_URL_TARGET_RESEARCH override the model and endpoint.
 */

import { runAgentLoop, type BoundTool, type WorkersAiLane } from "../signatures/_roteInference";
import { bindAgentTools, type RoteMcpEnv } from "./_roteMcp";
import { runWithTools } from "@cloudflare/ai-utils";

/** Tools the IR declared for this loop — the allowlist IS the boundary. */
const TOOLS: string[] = ["bright_data_search", "bright_data_scrape", "clinical_trials_search", "airweave_search", "salesforce_query"];

/** Servers searched for those tools, with the endpoints the IR recorded. */
const SERVERS: string[] = ["airweave", "brightdata", "clinicaltrials", "salesforce", "zoominfo"];
const SERVER_URLS: Record<string, string | null> = {"airweave": null, "brightdata": null, "clinicaltrials": null, "salesforce": null, "zoominfo": null};

/** Tools the IR resolved to a specific server — these bind from that
 * server and no other, so two servers exporting one tool name cannot
 * silently swap endpoints. Tools absent here fall back to first-wins
 * across SERVERS. */
const TOOL_SERVERS: Record<string, string> = {"airweave_search": "airweave", "bright_data_scrape": "brightdata", "bright_data_search": "brightdata", "clinical_trials_search": "clinicaltrials", "salesforce_query": "salesforce"};

export async function targetResearch(
    input: unknown,
    env: unknown, // the workflow's Env; cast below
): Promise<{ result: string; provider: string; iterations: number | null }> {
    const vars = env as Record<string, string | undefined>;
    const tools: BoundTool[] = await bindAgentTools(
        env as RoteMcpEnv,
        TOOLS,
        SERVERS,
        SERVER_URLS,
        TOOL_SERVERS,
    );
    const ai = (env as { AI?: unknown }).AI;
    const workersAi: WorkersAiLane | null = ai
        ? {
              binding: ai,
              model: vars.ROTE_WORKERS_AI_MODEL ?? "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
              runWithTools: runWithTools as WorkersAiLane["runWithTools"],
          }
        : null;
    return runAgentLoop({
        nodeId: "target_research",
        description: "Run external research (Bright Data web search, ClinicalTrials.gov)\nand internal research (Airweave enterprise search, Salesforce account\nhistory, internal publications) in parallel. Compile a short intel\nbrief covering pipeline, RWE/HEOR signals, key programs/teams, prior\naccount interactions, and validated TA experience.\n",
        task: input,
        model: vars.ROTE_MODEL_TARGET_RESEARCH ?? "claude-sonnet-4-6",
        tools,
        maxIterations: 10,
        baseUrl: vars.ROTE_BASE_URL_TARGET_RESEARCH ?? null,
        env: vars,
        workersAi,
    });
}
