/**
 * Typed LLM signature: personalize_email
 *
 * Generate personalized opening line and TA-relevant callout per
 *
 * Auto-generated by rote.adapters.cloudflare from the IR's
 * `signature_spec`. The non-determinism lives inside this module;
 * the workflow that calls it stays deterministic.
 */

import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";

export const PersonalizeEmailInput = z.object({
  "contact": z.object({
    "contact": z.object({
      "zoominfo_id": z.string(),
      "first_name": z.string(),
      "last_name": z.string(),
      "job_title": z.string(),
      "company_name": z.string(),
      "email": z.string().nullable().optional(),
      "phone": z.string().nullable().optional(),
      "mobile_phone": z.string().nullable().optional(),
      "accuracy_score": z.number().int().optional(),
      "linkedin_url": z.string().nullable().optional(),
      "employment_history": z.array(z.object({
        "company": z.string(),
        "title": z.string(),
        "start_year": z.number().int().nullable().optional(),
        "end_year": z.number().int().nullable().optional(),
      }).strict()).optional(),
      "direct_phone_dnc": z.boolean().optional(),
      "mobile_phone_dnc": z.boolean().optional(),
    }).strict(),
    "tier": z.enum(["ideal", "strong", "good"]),
    "relevance_evidence": z.string(),
  }).strict(),
  "intel": z.object({
    "pipeline_summary": z.string(),
    "rwe_signals": z.array(z.string()).optional(),
    "key_programs": z.array(z.string()).optional(),
    "prior_interactions": z.string().optional(),
    "relevant_experience": z.string().optional(),
    "messaging_angles": z.array(z.string()).optional(),
  }).strict(),
  "campaign_type": z.enum(["drug-specific", "condition-specific", "general-capabilities"]),
}).strict();
export type PersonalizeEmailInput = z.infer<typeof PersonalizeEmailInput>;

export const PersonalizeEmailOutput = z.object({
  "opening_line": z.string(),
  "ta_callout": z.string(),
}).strict();
export type PersonalizeEmailOutput = z.infer<typeof PersonalizeEmailOutput>;

const PROMPT = "Generate a personalized opening line and TA-relevant callout for an outreach email.\n\nLead with a specific observation about this contact's work \u2014 never generic. Ground the TA callout in our validated experience in the indication.\n\nContact: {{ contact }}\nIntel: {{ intel }}\nCampaign type: {{ campaign_type }}\n\nReturn both fields via the structured output tool.";

const OUTPUT_JSON_SCHEMA = {
  "additionalProperties": false,
  "properties": {
    "opening_line": {
      "title": "Opening Line",
      "type": "string"
    },
    "ta_callout": {
      "title": "Ta Callout",
      "type": "string"
    }
  },
  "required": [
    "opening_line",
    "ta_callout"
  ],
  "title": "PersonalizeEmailOutput",
  "type": "object"
};

function interpolate(template: string, vars: Record<string, unknown>): string {
    return template.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_match, key: string) => {
        const value = key.split(".").reduce<unknown>(
            (acc, part) =>
                acc != null && typeof acc === "object"
                    ? (acc as Record<string, unknown>)[part]
                    : undefined,
            vars,
        );
        if (value === undefined) {
            // A hole in a judge prompt produces confident garbage that is
            // far harder to debug than an error naming the missing field.
            throw new Error(
                `prompt template references {{ ${key} }} but the input has no ` +
                    `such field; available top-level keys: ${Object.keys(vars).sort().join(", ")}`,
            );
        }
        if (value === null) return "";
        return typeof value === "string" ? value : JSON.stringify(value);
    });
}

export async function personalizeEmail(
    rawInput: unknown,
    env: { ANTHROPIC_API_KEY: string },
): Promise<PersonalizeEmailOutput> {
    const input = PersonalizeEmailInput.parse(rawInput);
    const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });

    const response = await client.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 4096,
        tools: [
            {
                name: "personalize_email",
                description: "Generate personalized opening line and TA-relevant callout per",
                input_schema: OUTPUT_JSON_SCHEMA as { type: "object"; [k: string]: unknown },
            },
        ],
        tool_choice: { type: "tool", name: "personalize_email" },
        messages: [
            { role: "user", content: interpolate(PROMPT, input as Record<string, unknown>) },
        ],
    });

    const toolUse = response.content.find((b) => b.type === "tool_use");
    if (!toolUse || toolUse.type !== "tool_use") {
        throw new Error("LLM did not return a tool_use block for personalize_email");
    }
    return PersonalizeEmailOutput.parse(toolUse.input);
}
