/**
 * Typed LLM signature: vet_contact
 *
 * Apply the red-flags rubric (MSL, biomarker, translational, indication
 *
 * Auto-generated by rote.adapters.dbos_ts from the IR's
 * `signature_spec`. The non-determinism lives inside this module;
 * the workflow that calls it stays deterministic.
 */

import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";

export const VetContactInput = z.object({
  "contact": z.object({
    "zoominfo_id": z.string(),
    "first_name": z.string(),
    "last_name": z.string(),
    "job_title": z.string(),
    "company_name": z.string(),
    "email": z.string().nullable().optional(),
    "phone": z.string().nullable().optional(),
    "mobile_phone": z.string().nullable().optional(),
    "accuracy_score": z.number().int().optional(),
    "linkedin_url": z.string().nullable().optional(),
    "employment_history": z.array(z.object({
      "company": z.string(),
      "title": z.string(),
      "start_year": z.number().int().nullable().optional(),
      "end_year": z.number().int().nullable().optional(),
    }).strict()).optional(),
    "direct_phone_dnc": z.boolean().optional(),
    "mobile_phone_dnc": z.boolean().optional(),
  }).strict(),
  "brief": z.object({
    "drug_brand": z.string(),
    "drug_generic": z.string(),
    "condition_full": z.string(),
    "condition_acronym": z.string(),
    "therapeutic_area": z.string(),
    "manufacturer": z.string(),
    "campaign_type": z.enum(["drug-specific", "condition-specific", "general-capabilities"]),
    "target_quota": z.number().int(),
    "job_focus": z.enum(["medical", "rwe", "heor", "clinical-development"]).nullable().optional(),
  }).strict(),
  "intel": z.object({
    "pipeline_summary": z.string(),
    "rwe_signals": z.array(z.string()).optional(),
    "key_programs": z.array(z.string()).optional(),
    "prior_interactions": z.string().optional(),
    "relevant_experience": z.string().optional(),
    "messaging_angles": z.array(z.string()).optional(),
  }).strict(),
}).strict();
export type VetContactInput = z.infer<typeof VetContactInput>;

export const VetContactOutput = z.object({
  "decision": z.enum(["keep", "discard"]),
  "tier": z.enum(["ideal", "strong", "good"]).nullable().optional(),
  "discard_reason": z.enum(["indication_mismatch", "msl_role", "biomarker_discovery", "translational", "sales_commercial", "ops_strategy", "program_management", "low_accuracy", "no_valid_email", "other"]).nullable().optional(),
  "relevance_evidence": z.string(),
}).strict();
export type VetContactOutput = z.infer<typeof VetContactOutput>;

const PROMPT = "You are vetting a contact for a BDR outreach campaign.\n\nApply this rubric:\n- Discard if job title indicates MSL, Biomarker/Discovery, Translational Research, Sales/Commercial, Operations/Strategy, or Program Management.\n- Discard on indication mismatch with the campaign therapeutic area.\n- Tier surviving contacts: ideal / strong / good based on RWE/HEOR signal density.\n\nCore test: would this person commission, design, or approve a real-world evidence study?\n\nContact: {{ contact }}\nCampaign brief: {{ brief }}\nIntel brief: {{ intel }}\n\nReturn your decision via the structured output tool.";

const OUTPUT_JSON_SCHEMA = {
  "$defs": {
    "ContactTier": {
      "enum": [
        "ideal",
        "strong",
        "good"
      ],
      "title": "ContactTier",
      "type": "string"
    },
    "DiscardReason": {
      "enum": [
        "indication_mismatch",
        "msl_role",
        "biomarker_discovery",
        "translational",
        "sales_commercial",
        "ops_strategy",
        "program_management",
        "low_accuracy",
        "no_valid_email",
        "other"
      ],
      "title": "DiscardReason",
      "type": "string"
    },
    "VetDecision": {
      "enum": [
        "keep",
        "discard"
      ],
      "title": "VetDecision",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "properties": {
    "decision": {
      "$ref": "#/$defs/VetDecision"
    },
    "tier": {
      "anyOf": [
        {
          "$ref": "#/$defs/ContactTier"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "discard_reason": {
      "anyOf": [
        {
          "$ref": "#/$defs/DiscardReason"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "relevance_evidence": {
      "title": "Relevance Evidence",
      "type": "string"
    }
  },
  "required": [
    "decision",
    "relevance_evidence"
  ],
  "title": "VetContactOutput",
  "type": "object"
};

function interpolate(template: string, vars: Record<string, unknown>): string {
    return template.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_match, key: string) => {
        const value = key.split(".").reduce<unknown>(
            (acc, part) =>
                acc != null && typeof acc === "object"
                    ? (acc as Record<string, unknown>)[part]
                    : undefined,
            vars,
        );
        if (value === undefined) {
            // A hole in a judge prompt produces confident garbage that is
            // far harder to debug than an error naming the missing field.
            throw new Error(
                `prompt template references {{ ${key} }} but the input has no ` +
                    `such field; available top-level keys: ${Object.keys(vars).sort().join(", ")}`,
            );
        }
        if (value === null) return "";
        return typeof value === "string" ? value : JSON.stringify(value);
    });
}

export async function vetContact(
    rawInput: unknown,
    env: {
        ANTHROPIC_API_KEY: string;
        // Operator overrides — swap the model or endpoint without re-emitting.
        ROTE_MODEL_VET_CONTACT?: string;
        ROTE_BASE_URL_VET_CONTACT?: string;
    },
): Promise<VetContactOutput> {
    const input = VetContactInput.parse(rawInput);
    const client = new Anthropic({
        apiKey: env.ANTHROPIC_API_KEY,
        baseURL: env.ROTE_BASE_URL_VET_CONTACT,
    });

    const response = await client.messages.create({
        model: env.ROTE_MODEL_VET_CONTACT ?? "claude-sonnet-4-6",
        max_tokens: 4096,
        tools: [
            {
                name: "vet_contact",
                description: "Apply the red-flags rubric (MSL, biomarker, translational, indication",
                input_schema: OUTPUT_JSON_SCHEMA as { type: "object"; [k: string]: unknown },
            },
        ],
        tool_choice: { type: "tool", name: "vet_contact" },
        messages: [
            { role: "user", content: interpolate(PROMPT, input as Record<string, unknown>) },
        ],
    });

    const toolUse = response.content.find((b) => b.type === "tool_use");
    if (!toolUse || toolUse.type !== "tool_use") {
        throw new Error("LLM did not return a tool_use block for vet_contact");
    }
    return VetContactOutput.parse(toolUse.input);
}
