/**
 * Auto-generated by rote.adapters.inngest.
 *
 * Minimal framework-neutral serve entrypoint: a plain Node HTTP server
 * wrapping the Inngest serve handler (which answers on every path).
 * This is what the local dev server
 * (`npx inngest-cli dev -u http://localhost:3000`) and
 * Inngest Cloud sync against.
 *
 * Mounting the same functions inside an existing Next.js / Express app
 * instead: see README.md — import { runPipeline } and use the
 * framework's serve adapter (`inngest/next`, `inngest/express`).
 */

import http from "node:http";
import { serve } from "inngest/node";
import { inngest } from "./inngest/client";
import { runPipeline } from "./inngest/pipeline";

const handler = serve({ client: inngest, functions: [runPipeline] });

const server = http.createServer(handler);

const port = Number(process.env.PORT ?? 3000);
server.listen(port, () => {
    console.log(`inngest functions served on :${port} (app: bdr-campaign)`);
});
