/**
 * Auto-generated by rote.adapters.dbos_ts.
 *
 * Pipeline: bdr-campaign v0.1.0
 * Source skill: ../../skill
 * Pipeline hash: fef3f728
 *
 * DO NOT EDIT BY HAND. Re-run `rote emit --runtime dbos-ts` to regenerate.
 *
 * Workflow versioning: the registered workflow name includes a hash of
 * the pipeline so regenerated pipelines become a new workflow type.
 * In-flight workflows recover onto the code they started with; new
 * starts use the new code.
 *
 * Architecture note: every step in this file wraps a deterministic
 * function from `extracted/` or a typed LLM signature from
 * `signatures/`. None of them call MCP tools at runtime — the MCP
 * tool calls from the source skill were graduated into direct API
 * calls during the rote emission step.
 */

import { DBOS } from "@dbos-inc/dbos-sdk";

import { targetResearch } from "./extracted/target_research";
import { taxonomyLookup } from "./extracted/taxonomy_lookup";
import { leadGenerationLoop } from "./extracted/lead_generation_loop";
import { enrichContactBatch } from "./extracted/enrich_contact_batch";
import { vetContact } from "./signatures/vet_contact";
import { hubspotUpsert } from "./extracted/hubspot_upsert";
import { hubspotCreateList } from "./extracted/hubspot_create_list";
import { exclusionCheckDnc } from "./extracted/exclusion_check_dnc";
import { exclusionCheckRecent } from "./extracted/exclusion_check_recent";
import { exclusionCheckSequence } from "./extracted/exclusion_check_sequence";
import { personalizeEmail } from "./signatures/personalize_email";
import { createSalesTemplate } from "./extracted/create_sales_template";
import { preEnrollmentReport } from "./extracted/pre_enrollment_report";

function requireEnv(name: string): string {
    const value = process.env[name];
    if (!value) {
        throw new Error(`missing required environment variable ${name}`);
    }
    return value;
}

// ───────── Steps ─────────
//
// One durable step per node (loop-body sub-nodes included, so they
// stay testable in isolation). DBOS checkpoints every step result to
// the system database; a crashed process resumes after the last
// completed step.

/**
 * Run external research (Bright Data web search, ClinicalTrials.gov)
 *
 * Agent loop — bounded, tool-restricted. The stub in
 * `extracted/target_research` throws until implemented against an
 * agent harness.
 */
export const targetResearchStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => targetResearch(payload),
    { name: "target_research", retriesAllowed: true, maxAttempts: 3, backoffRate: 2, timeoutMS: 300000 },
);

/**
 * Resolve ZoomInfo IDs for management levels (VP, Director), industries
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/taxonomy_lookup` for the implementation.
 */
export const taxonomyLookupStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => taxonomyLookup(payload),
    { name: "taxonomy_lookup" },
);

/**
 * Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo
 *
 * Agent loop — bounded, tool-restricted. The stub in
 * `extracted/lead_generation_loop` throws until implemented against an
 * agent harness.
 */
export const leadGenerationLoopStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => leadGenerationLoop(payload),
    { name: "lead_generation_loop", timeoutMS: 900000 },
);

/**
 * Batch enrich contacts via ZoomInfo. Always requests employmentHistory
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/enrich_contact_batch` for the implementation.
 */
// retry_on categories from the IR: rate_limit, network. DBOS retries any
// exception; narrow with the StepConfig `shouldRetry` predicate if needed.
export const enrichContactBatchStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => enrichContactBatch(payload),
    { name: "enrich_contact_batch", retriesAllowed: true, maxAttempts: 6, backoffRate: 2, timeoutMS: 30000 },
);

/**
 * Apply the red-flags rubric (MSL, biomarker, translational, indication
 *
 * LLM judge — typed input/output, bounded decision space. The
 * non-determinism lives inside this step, not the workflow.
 */
export const vetContactStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => vetContact(payload, {
        ANTHROPIC_API_KEY: requireEnv("ANTHROPIC_API_KEY"),
        ROTE_MODEL_VET_CONTACT: process.env.ROTE_MODEL_VET_CONTACT,
        ROTE_BASE_URL_VET_CONTACT: process.env.ROTE_BASE_URL_VET_CONTACT,
    }),
    { name: "vet_contact" },
);

/**
 * Batch upsert contacts to HubSpot (create or update by email). Hard
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/hubspot_upsert` for the implementation.
 */
export const hubspotUpsertStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => hubspotUpsert(payload),
    { name: "hubspot_upsert", retriesAllowed: true, maxAttempts: 6, backoffRate: 2, timeoutMS: 60000 },
);

/**
 * Create a static list named after the campaign and add the upserted
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/hubspot_create_list` for the implementation.
 */
export const hubspotCreateListStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => hubspotCreateList(payload),
    { name: "hubspot_create_list", retriesAllowed: true, maxAttempts: 6, backoffRate: 2 },
);

/**
 * For each contact, look up "BDR do not contact" list memberships.
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/exclusion_check_dnc` for the implementation.
 *
 * MANDATORY: this node was marked mandatory in the source skill.
 * The workflow always calls it; do not make it conditional.
 */
export const exclusionCheckDncStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => exclusionCheckDnc(payload),
    { name: "exclusion_check_dnc" },
);

/**
 * For each contact, check if they were emailed (outbound) in the last
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/exclusion_check_recent` for the implementation.
 *
 * MANDATORY: this node was marked mandatory in the source skill.
 * The workflow always calls it; do not make it conditional.
 */
export const exclusionCheckRecentStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => exclusionCheckRecent(payload),
    { name: "exclusion_check_recent" },
);

/**
 * For each contact, check if they are already enrolled in an active
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/exclusion_check_sequence` for the implementation.
 *
 * MANDATORY: this node was marked mandatory in the source skill.
 * The workflow always calls it; do not make it conditional.
 */
export const exclusionCheckSequenceStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => exclusionCheckSequence(payload),
    { name: "exclusion_check_sequence" },
);

/**
 * Generate personalized opening line and TA-relevant callout per
 *
 * LLM judge — typed input/output, bounded decision space. The
 * non-determinism lives inside this step, not the workflow.
 */
export const personalizeEmailStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => personalizeEmail(payload, {
        ANTHROPIC_API_KEY: requireEnv("ANTHROPIC_API_KEY"),
        ROTE_MODEL_PERSONALIZE_EMAIL: process.env.ROTE_MODEL_PERSONALIZE_EMAIL,
        ROTE_BASE_URL_PERSONALIZE_EMAIL: process.env.ROTE_BASE_URL_PERSONALIZE_EMAIL,
    }),
    { name: "personalize_email" },
);

/**
 * Create or update HubSpot sales templates for the campaign sequence
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/create_sales_template` for the implementation.
 */
export const createSalesTemplateStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => createSalesTemplate(payload),
    { name: "create_sales_template", retriesAllowed: true, maxAttempts: 4, backoffRate: 2 },
);

/**
 * Generate the final pre-enrollment report (markdown) with totals,
 *
 * Graduated from MCP tool call → deterministic API call. See
 * `extracted/pre_enrollment_report` for the implementation.
 */
export const preEnrollmentReportStep = DBOS.registerStep(
    async (payload: Record<string, unknown>) => preEnrollmentReport(payload),
    { name: "pre_enrollment_report" },
);

// ───────── Workflow ─────────

function unwrap<T>(settled: PromiseSettledResult<T>): T {
    if (settled.status === "rejected") {
        // Rethrow the step's original error — DBOS already logged which
        // step failed, and downstream debugging wants the real cause.
        throw settled.reason;
    }
    return settled.value;
}

/**
 * End-to-end BDR outreach campaign workflow for pharma/biotech research
 */
export const runPipeline = DBOS.registerWorkflow(
    async (pipelineInput: Record<string, unknown>): Promise<Record<string, unknown>> => {
        // ─── Wave 1 ───
        // Parallel fan-out: run every step in the wave concurrently
        // and settle them all — Promise.allSettled per the DBOS docs
        // (a bare Promise.all can crash the Node process on unhandled
        // rejections).
        const [target_research_settled, taxonomy_lookup_settled] = await Promise.allSettled([
            targetResearchStep({
                brief: pipelineInput,
            }),
            taxonomyLookupStep({
                brief: pipelineInput,
            }),
        ]);
        const target_research_result = unwrap(target_research_settled);
        const taxonomy_lookup_result = unwrap(taxonomy_lookup_settled);

        // ─── Wave 2 ───
        const lead_generation_loop_result = await leadGenerationLoopStep(
            {
                brief: pipelineInput,
                intel: target_research_result,
                taxonomy: taxonomy_lookup_result,
                target_quota: pipelineInput["target_quota"],
            },
        );

        // ─── Wave 3 ───
        // ─── HITL gate: contact_review_gate ───
        // Durable receive: the workflow parks in the system database until
        // DBOS.send(workflowID, payload, "contact_review_approved")
        // delivers the resume message. Survives process restarts. The
        // timeout is explicit — DBOS.recv defaults to 60s when omitted.
        const contact_review_gate_result = await DBOS.recv<Record<string, unknown>>(
            "contact_review_approved",
            604800, // 7d
        );
        if (contact_review_gate_result === null) {
            throw new Error(
                "HITL gate 'contact_review_gate' timed out after 7d waiting " +
                    "for signal 'contact_review_approved'",
            );
        }

        // ─── Wave 4 ───
        const hubspot_upsert_result = await hubspotUpsertStep(
            {
                contacts: (contact_review_gate_result as Record<string, unknown>)["approved_contacts"],
            },
        );

        // ─── Wave 5 ───
        const hubspot_create_list_result = await hubspotCreateListStep(
            {
                campaign_name: pipelineInput["drug_brand"],
                contacts: (hubspot_upsert_result as Record<string, unknown>)["upserted"],
            },
        );

        // ─── Wave 6 ───
        const exclusion_check_dnc_result = await exclusionCheckDncStep(
            {
                contacts: (hubspot_upsert_result as Record<string, unknown>)["upserted"],
            },
        );

        // ─── Wave 7 ───
        const exclusion_check_recent_result = await exclusionCheckRecentStep(
            {
                contacts: (exclusion_check_dnc_result as Record<string, unknown>)["passed"],
            },
        );

        // ─── Wave 8 ───
        const exclusion_check_sequence_result = await exclusionCheckSequenceStep(
            {
                contacts: (exclusion_check_recent_result as Record<string, unknown>)["passed"],
            },
        );

        // ─── Wave 9 ───
        const personalize_email_result = await personalizeEmailStep(
            {
                contact: (exclusion_check_sequence_result as Record<string, unknown>)["passed"],
                intel: target_research_result,
                campaign_type: pipelineInput["campaign_type"],
            },
        );

        // ─── Wave 10 ───
        const create_sales_template_result = await createSalesTemplateStep(
            {
                campaign_name: pipelineInput["drug_brand"],
                personalizations: personalize_email_result,
            },
        );

        // ─── Wave 11 ───
        const pre_enrollment_report_result = await preEnrollmentReportStep(
            {
                campaign_name: pipelineInput["drug_brand"],
                passed_contacts: (exclusion_check_sequence_result as Record<string, unknown>)["passed"],
                exclusions: (exclusion_check_sequence_result as Record<string, unknown>)["excluded"],
                template_ids: (create_sales_template_result as Record<string, unknown>)["template_ids"],
            },
        );

        // ─── Wave 12 ───
        // ─── HITL gate: manual_enrollment_handoff ───
        // Durable receive: the workflow parks in the system database until
        // DBOS.send(workflowID, payload, "bdr_enrollment_complete")
        // delivers the resume message. Survives process restarts. The
        // timeout is explicit — DBOS.recv defaults to 60s when omitted.
        const manual_enrollment_handoff_result = await DBOS.recv<Record<string, unknown>>(
            "bdr_enrollment_complete",
            1209600, // 14d
        );
        if (manual_enrollment_handoff_result === null) {
            throw new Error(
                "HITL gate 'manual_enrollment_handoff' timed out after 14d waiting " +
                    "for signal 'bdr_enrollment_complete'",
            );
        }

        return {
            "manual_enrollment_handoff": manual_enrollment_handoff_result as Record<string, unknown>,
        };
    },
    { name: "BdrCampaign_fef3f728" },
);

// ───────── Entrypoint ─────────

export async function main(): Promise<void> {
    DBOS.setConfig({
        name: "bdr-campaign",
        // undefined → the SDK default
        // (postgresql://postgres:dbos@localhost:5432/<name>_dbos_sys),
        // which matches `npx dbos postgres start`. The TS SDK is
        // Postgres-only — unlike DBOS Python there is no SQLite mode.
        systemDatabaseUrl: process.env.DBOS_SYSTEM_DATABASE_URL,
        // The admin server (port 3001) is opt-in; enable it when you
        // want the DBOS console / management API.
        runAdminServer: false,
    });
    await DBOS.launch();
    try {
        const pipelineInput = JSON.parse(
            process.argv[2] ?? "{}",
        ) as Record<string, unknown>;
        const handle = await DBOS.startWorkflow(runPipeline)(pipelineInput);
        console.error(`workflow started: ${handle.workflowID}`);
        console.log(JSON.stringify(await handle.getResult(), null, 2));
    } finally {
        await DBOS.shutdown();
    }
}

if (require.main === module) {
    main().catch((err) => {
        console.error(err);
        process.exitCode = 1;
    });
}
