/**
 * Auto-generated by rote.adapters.inngest.
 *
 * The Inngest client for the bdr-campaign pipeline. In dev the SDK
 * auto-detects the local dev server via INNGEST_DEV=1; in production
 * set INNGEST_EVENT_KEY (for sends) and INNGEST_SIGNING_KEY (for the
 * serve handler) in the environment.
 */

import { Inngest } from "inngest";

export const inngest = new Inngest({ id: "bdr-campaign" });
