/**
 * Auto-generated by rote.adapters.inngest.
 *
 * Pipeline: bdr-campaign v0.1.0
 * Source skill: ../skill
 * Pipeline hash: 68ef477f
 *
 * DO NOT EDIT BY HAND. Re-run `rote emit --runtime inngest` to regenerate.
 *
 * Function versioning: the function id includes a hash of the pipeline
 * so a regenerated pipeline becomes a new Inngest function. The trigger
 * event name stays stable across versions — senders never change.
 *
 * Architecture note: every step in this function wraps a deterministic
 * function from `extracted/` or a typed LLM signature from
 * `signatures/`. None of them call MCP tools at runtime — the MCP
 * tool calls from the source skill were compiled into direct API
 * calls during the rote emission step.
 */

import { NonRetriableError } from "inngest";
import { inngest } from "./client";
import { targetResearch } from "../extracted/target_research";
import { taxonomyLookup } from "../extracted/taxonomy_lookup";
import { leadGenerationLoop } from "../extracted/lead_generation_loop";
import { enrichContactBatch } from "../extracted/enrich_contact_batch";
import { vetContact } from "../signatures/vet_contact";
import { hubspotUpsert } from "../extracted/hubspot_upsert";
import { hubspotCreateList } from "../extracted/hubspot_create_list";
import { exclusionCheckDnc } from "../extracted/exclusion_check_dnc";
import { exclusionCheckRecent } from "../extracted/exclusion_check_recent";
import { exclusionCheckSequence } from "../extracted/exclusion_check_sequence";
import { personalizeEmail } from "../signatures/personalize_email";
import { createSalesTemplate } from "../extracted/create_sales_template";
import { preEnrollmentReport } from "../extracted/pre_enrollment_report";

function requireEnv(name: string): string {
    const value = process.env[name];
    if (!value) {
        throw new Error(`missing required environment variable ${name}`);
    }
    return value;
}

/**
 * End-to-end BDR outreach campaign workflow for pharma/biotech research
 */
export const runPipeline = inngest.createFunction(
    {
        id: "bdr-campaign-68ef477f",
        // Inngest v4 retries are function-level: every step gets this
        // budget (managed exponential backoff + jitter). Set to the max
        // across the IR's per-node retry policies; per-node deltas are
        // documented on the affected steps below.
        retries: 5,
        triggers: [{ event: "bdr-campaign/run.requested" }],
    },
    async ({ event, step }) => {
        const pipelineInput = event.data as Record<string, unknown>;

        // ─── Wave 1 ───
        // Parallel fan-out: Promise.all over step.run calls is
        // Inngest's documented in-function parallelism pattern —
        // the executor schedules the steps concurrently.
        // MCP-backed branches park independently; one broadcast
        // of the release event wakes all of them.
        // IR retry policy: max 2 (exponential). Inngest v4
        // retries are function-level only — this step gets the function's
        // budget of 5 with managed exponential backoff + jitter.
        // Throw NonRetriableError inside the step to stop retries early.
        // IR timeout 5m: Inngest v4 has no per-step timeout —
        // enforce inside the implementation (AbortSignal.timeout) if needed.
        const [target_research_result, taxonomy_lookup_result] = await Promise.all([
            step.run("target_research", async () => targetResearch({
                    brief: pipelineInput,
                })),
            step.run("taxonomy_lookup", async () => taxonomyLookup({
                    brief: pipelineInput,
                })),
        ]);

        // ─── Wave 2 ───
        // IR timeout 15m: Inngest v4 has no per-step timeout —
        // enforce inside the implementation (AbortSignal.timeout) if needed.
        const lead_generation_loop_result = await step.run("lead_generation_loop", async () => leadGenerationLoop({
                brief: pipelineInput,
                intel: target_research_result,
                taxonomy: taxonomy_lookup_result,
                target_quota: pipelineInput["target_quota"],
            }));

        // ─── Wave 3 ───
        // ─── HITL gate: contact_review_gate ───
        // The run parks durably until an event named 'bdr-campaign/contact_review_approved'
        // arrives (inngest.send / POST to the event API). waitForEvent
        // returns null on timeout — and a timed-out wait is memoized, so
        // retrying could never conjure the missing approval. Throw
        // NonRetriableError: silence is not approval.
        const contact_review_gate_event = await step.waitForEvent(
            "contact_review_gate",
            { event: "bdr-campaign/contact_review_approved", timeout: "7d" },
        );
        if (contact_review_gate_event === null) {
            throw new NonRetriableError(
                "HITL gate 'contact_review_gate' timed out after 7d waiting " +
                    "for event 'bdr-campaign/contact_review_approved'",
            );
        }
        const contact_review_gate_result = contact_review_gate_event.data as Record<string, unknown>;

        // ─── Wave 4 ───
        // IR timeout 60s: Inngest v4 has no per-step timeout —
        // enforce inside the implementation (AbortSignal.timeout) if needed.
        const hubspot_upsert_result = await step.run("hubspot_upsert", async () => hubspotUpsert({
                contacts: (contact_review_gate_result as Record<string, unknown>)["approved_contacts"],
            }));

        // ─── Wave 5 ───
        const hubspot_create_list_result = await step.run("hubspot_create_list", async () => hubspotCreateList({
                campaign_name: pipelineInput["drug_brand"],
                contacts: (hubspot_upsert_result as Record<string, unknown>)["upserted"],
            }));

        // ─── Wave 6 ───
        const exclusion_check_dnc_result = await step.run("exclusion_check_dnc", async () => exclusionCheckDnc({
                contacts: (hubspot_upsert_result as Record<string, unknown>)["upserted"],
            }));

        // ─── Wave 7 ───
        const exclusion_check_recent_result = await step.run("exclusion_check_recent", async () => exclusionCheckRecent({
                contacts: (exclusion_check_dnc_result as Record<string, unknown>)["passed"],
            }));

        // ─── Wave 8 ───
        const exclusion_check_sequence_result = await step.run("exclusion_check_sequence", async () => exclusionCheckSequence({
                contacts: (exclusion_check_recent_result as Record<string, unknown>)["passed"],
            }));

        // ─── Wave 9 ───
        const personalize_email_result = await step.run("personalize_email", async () => personalizeEmail({
                contact: (exclusion_check_sequence_result as Record<string, unknown>)["passed"],
                intel: target_research_result,
                campaign_type: pipelineInput["campaign_type"],
            }, {
        ANTHROPIC_API_KEY: requireEnv("ANTHROPIC_API_KEY"),
        ROTE_MODEL_PERSONALIZE_EMAIL: process.env.ROTE_MODEL_PERSONALIZE_EMAIL,
        ROTE_BASE_URL_PERSONALIZE_EMAIL: process.env.ROTE_BASE_URL_PERSONALIZE_EMAIL,
    }));

        // ─── Wave 10 ───
        // IR retry policy: max 3 (exponential). Inngest v4
        // retries are function-level only — this step gets the function's
        // budget of 5 with managed exponential backoff + jitter.
        // Throw NonRetriableError inside the step to stop retries early.
        const create_sales_template_result = await step.run("create_sales_template", async () => createSalesTemplate({
                campaign_name: pipelineInput["drug_brand"],
                personalizations: personalize_email_result,
            }));

        // ─── Wave 11 ───
        const pre_enrollment_report_result = await step.run("pre_enrollment_report", async () => preEnrollmentReport({
                campaign_name: pipelineInput["drug_brand"],
                passed_contacts: (exclusion_check_sequence_result as Record<string, unknown>)["passed"],
                exclusions: (exclusion_check_sequence_result as Record<string, unknown>)["excluded"],
                template_ids: (create_sales_template_result as Record<string, unknown>)["template_ids"],
            }));

        // ─── Wave 12 ───
        // ─── HITL gate: manual_enrollment_handoff ───
        // The run parks durably until an event named 'bdr-campaign/bdr_enrollment_complete'
        // arrives (inngest.send / POST to the event API). waitForEvent
        // returns null on timeout — and a timed-out wait is memoized, so
        // retrying could never conjure the missing approval. Throw
        // NonRetriableError: silence is not approval.
        const manual_enrollment_handoff_event = await step.waitForEvent(
            "manual_enrollment_handoff",
            { event: "bdr-campaign/bdr_enrollment_complete", timeout: "14d" },
        );
        if (manual_enrollment_handoff_event === null) {
            throw new NonRetriableError(
                "HITL gate 'manual_enrollment_handoff' timed out after 14d waiting " +
                    "for event 'bdr-campaign/bdr_enrollment_complete'",
            );
        }
        const manual_enrollment_handoff_result = manual_enrollment_handoff_event.data as Record<string, unknown>;

        return {
            "manual_enrollment_handoff": manual_enrollment_handoff_result as Record<string, unknown>,
        };
    },
);
