/**
 * MCP connection helper (generated by rote — do not edit; the source
 * of truth is rote.adapters._ts_common.ROTE_MCP_HELPER_TS).
 *
 * Mirrors the rote CLI's behavior exactly:
 * - Endpoint: ROTE_MCP_<SERVER>_URL env var > the rote registry
 *   (~/.config/rote/mcp.json) > the endpoint recorded in the pipeline.
 * - Auth: the rote token store (~/.local/share/rote/mcp-tokens/<server>.json,
 *   written by `rote mcp login`), refreshing stale access tokens via the
 *   OAuth refresh grant and writing rotated tokens back atomically; else
 *   static headers from the registry entry; else unauthenticated.
 * - Never interactive: anything that needs a human (no refresh path, a
 *   401 the refresh cannot fix) throws RoteMcpAuthNeeded — the emitted
 *   workflow parks durably on it until `rote mcp login <server>` (or a
 *   re-provisioned credential) releases it.
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import {
    StreamableHTTPClientTransport,
    StreamableHTTPError,
} from "@modelcontextprotocol/sdk/client/streamableHttp.js";

/**
 * The MCP server needs a human to (re)authenticate.
 *
 * Detect with isRoteMcpAuthNeeded(), never `instanceof`: durable runtimes
 * (DBOS, Inngest) serialize step errors across replay/process boundaries
 * and reconstruct plain Errors — class identity is lost, but `name` and
 * own enumerable properties survive.
 */
export class RoteMcpAuthNeeded extends Error {
    readonly server: string;
    readonly reason: string;

    constructor(server: string, reason: string) {
        super(
            `MCP server '${server}' needs (re)authentication — ${reason}. ` +
                `Run: rote mcp login ${server}`,
        );
        this.name = "RoteMcpAuthNeeded";
        this.server = server;
        this.reason = reason;
    }
}

/** True if a RoteMcpAuthNeeded hides anywhere in the error tree
 * (cause chains from step wrappers, `errors` arrays from retry
 * exhaustion / AggregateError). */
export function isRoteMcpAuthNeeded(err: unknown): boolean {
    let node: unknown = err;
    for (let depth = 0; node != null && depth < 16; depth++) {
        const e = node as { name?: unknown; errors?: unknown; cause?: unknown };
        if (e.name === "RoteMcpAuthNeeded") return true;
        if (Array.isArray(e.errors) && e.errors.some((sub) => isRoteMcpAuthNeeded(sub))) {
            return true;
        }
        node = e.cause;
    }
    return false;
}

interface TokenDoc {
    version?: number;
    server_url?: string;
    tokens: {
        access_token?: string;
        token_type?: string;
        expires_in?: number;
        refresh_token?: string;
        scope?: string;
    } | null;
    expires_at: number | null;
    client_info: { client_id?: string; client_secret?: string } | null;
    token_endpoint: string | null;
}

interface RegistryEntry {
    url?: string;
    client_id?: string;
    client_secret?: string;
    headers?: Record<string, string>;
}

function registryServers(): Record<string, RegistryEntry> {
    const override = process.env.ROTE_MCP_CONFIG;
    const base = process.env.XDG_CONFIG_HOME ?? path.join(os.homedir(), ".config");
    const file = override ?? path.join(base, "rote", "mcp.json");
    if (!fs.existsSync(file)) return {};
    const data = JSON.parse(fs.readFileSync(file, "utf-8")) as {
        servers?: Record<string, RegistryEntry>;
    };
    return data.servers ?? {};
}

function tokenDir(): string {
    const override = process.env.ROTE_MCP_TOKEN_DIR;
    if (override) return override;
    const base = process.env.XDG_DATA_HOME ?? path.join(os.homedir(), ".local", "share");
    return path.join(base, "rote", "mcp-tokens");
}

export function resolveUrl(server: string, pipelineUrl: string | null): string {
    const envUrl = process.env[`ROTE_MCP_${server.toUpperCase()}_URL`];
    if (envUrl) return envUrl;
    const entry = registryServers()[server];
    if (entry?.url) return entry.url;
    if (pipelineUrl) return pipelineUrl;
    throw new Error(
        `no endpoint for MCP server '${server}' — register it ` +
            `(rote mcp add ${server} <url>) or set ROTE_MCP_${server.toUpperCase()}_URL`,
    );
}

function readTokenDoc(server: string): TokenDoc | null {
    const file = path.join(tokenDir(), `${server}.json`);
    if (!fs.existsSync(file)) return null;
    return JSON.parse(fs.readFileSync(file, "utf-8")) as TokenDoc;
}

function writeTokenDoc(server: string, doc: TokenDoc): void {
    // Same discipline as the Python side: atomic replace, 0600. The CLI
    // and other workflows read this file concurrently.
    const dir = tokenDir();
    fs.mkdirSync(dir, { recursive: true });
    doc.version = doc.version ?? 1;
    const tmp = path.join(dir, `.${server}-${process.pid}-${Date.now()}.tmp`);
    fs.writeFileSync(tmp, JSON.stringify(doc, null, 2) + "\n", { mode: 0o600 });
    fs.renameSync(tmp, path.join(dir, `${server}.json`));
}

async function refreshAccessToken(server: string, doc: TokenDoc): Promise<string> {
    const refreshToken = doc.tokens?.refresh_token;
    if (!refreshToken) {
        throw new RoteMcpAuthNeeded(
            server,
            "the access token is expired and no refresh token is stored",
        );
    }
    if (!doc.token_endpoint) {
        throw new RoteMcpAuthNeeded(
            server,
            "the token store has no token_endpoint (written by rote mcp login)",
        );
    }
    const entry = registryServers()[server];
    const clientId = doc.client_info?.client_id ?? entry?.client_id;
    const clientSecret = doc.client_info?.client_secret ?? entry?.client_secret;
    if (!clientId) {
        throw new RoteMcpAuthNeeded(server, "no client_id is stored for the refresh grant");
    }
    const body = new URLSearchParams({
        grant_type: "refresh_token",
        refresh_token: refreshToken,
        client_id: clientId,
    });
    if (clientSecret) body.set("client_secret", clientSecret);
    const response = await fetch(doc.token_endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: body.toString(),
    });
    if (!response.ok) {
        throw new RoteMcpAuthNeeded(server, `the refresh grant failed (${response.status})`);
    }
    const granted = (await response.json()) as {
        access_token: string;
        expires_in?: number;
        refresh_token?: string;
        token_type?: string;
        scope?: string;
    };
    // Persist the rotated credentials: some servers rotate the refresh
    // token on every use — losing the new one strands every consumer.
    doc.tokens = {
        ...doc.tokens,
        access_token: granted.access_token,
        token_type: granted.token_type ?? doc.tokens?.token_type ?? "Bearer",
        expires_in: granted.expires_in,
        refresh_token: granted.refresh_token ?? refreshToken,
        scope: granted.scope ?? doc.tokens?.scope,
    };
    doc.expires_at =
        granted.expires_in != null ? Date.now() / 1000 + granted.expires_in : null;
    writeTokenDoc(server, doc);
    return granted.access_token;
}

/** Currently-valid auth headers for `server`, or null (unauthenticated). */
export async function freshHeaders(
    server: string,
    forceRefresh = false,
): Promise<Record<string, string> | null> {
    const entry = registryServers()[server];
    if (entry?.headers && Object.keys(entry.headers).length > 0) {
        return { ...entry.headers };
    }
    const doc = readTokenDoc(server);
    const access = doc?.tokens?.access_token;
    if (!doc || !access) return null;
    const staleAt = doc.expires_at != null ? doc.expires_at - 60 : null;
    const isStale = forceRefresh || (staleAt != null && Date.now() / 1000 >= staleAt);
    const token = isStale ? await refreshAccessToken(server, doc) : access;
    return { Authorization: `Bearer ${token}` };
}

/**
 * Run `fn` against a connected, authenticated MCP session.
 *
 * Every operation shares one auth story: try with current credentials,
 * and on a 401 (revoked or expired-early token) refresh once and retry
 * on a fresh transport. Anything a refresh cannot fix becomes
 * RoteMcpAuthNeeded so the workflow parks instead of failing.
 */
async function withMcpSession<T>(
    server: string,
    pipelineUrl: string | null,
    fn: (client: Client) => Promise<T>,
): Promise<T> {
    const url = resolveUrl(server, pipelineUrl);

    const attempt = async (headers: Record<string, string> | null) => {
        const client = new Client({ name: "rote-pipeline", version: "1.0.0" });
        const transport = new StreamableHTTPClientTransport(new URL(url), {
            requestInit: headers ? { headers } : undefined,
        });
        try {
            await client.connect(transport);
            return await fn(client);
        } finally {
            await client.close().catch(() => undefined);
        }
    };

    try {
        return await attempt(await freshHeaders(server));
    } catch (err) {
        if (!isUnauthorized(err)) throw err;
        if (!readTokenDoc(server)?.tokens?.refresh_token) {
            throw new RoteMcpAuthNeeded(server, "the server returned 401 Unauthorized");
        }
        try {
            return await attempt(await freshHeaders(server, true));
        } catch (retryErr) {
            if (isUnauthorized(retryErr)) {
                throw new RoteMcpAuthNeeded(
                    server,
                    "the server returned 401 even after a token refresh",
                );
            }
            throw retryErr;
        }
    }
}

/**
 * Call one tool on an MCP server, authenticated from the rote credential
 * store. On a 401 (revoked/expired-early token) the call refreshes once
 * and retries with a fresh transport.
 */
export async function callMcpTool(
    server: string,
    pipelineUrl: string | null,
    tool: string,
    args: Record<string, unknown>,
): Promise<Record<string, unknown>> {
    return withMcpSession(server, pipelineUrl, async (client) => {
        const result = await client.callTool({ name: tool, arguments: args });
        if (result.isError) {
            throw new Error(
                `MCP tool '${tool}' on '${server}' returned an error: ` +
                    JSON.stringify(result.content),
            );
        }
        if (result.structuredContent) {
            return result.structuredContent as Record<string, unknown>;
        }
        const text = (result.content as Array<{ type: string; text?: string }>).find(
            (block) => block.type === "text",
        )?.text;
        return (text ? JSON.parse(text) : {}) as Record<string, unknown>;
    });
}

/** One tool as the server advertises it. */
export interface McpToolSpec {
    name: string;
    description: string;
    inputSchema: Record<string, unknown>;
}

/**
 * Every tool `server` advertises, with the JSON Schema it declares.
 *
 * An agent_loop names bare tools; the schema the model needs to call one
 * correctly lives on the server, not in the IR. Fetching it here means
 * the agent's tool contract is always the server's current contract —
 * it cannot go stale the way a schema copied into the pipeline would.
 */
export async function listMcpTools(
    server: string,
    pipelineUrl: string | null,
): Promise<McpToolSpec[]> {
    return withMcpSession(server, pipelineUrl, async (client) => {
        const { tools } = await client.listTools();
        return tools.map((tool) => ({
            name: tool.name,
            description: tool.description ?? "",
            inputSchema: (tool.inputSchema ?? {
                type: "object",
                properties: {},
            }) as Record<string, unknown>,
        }));
    });
}

/** A tool bound to a callable — structurally a BoundTool for the agent loop. */
export interface BoundMcpTool {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
    run: (args: Record<string, unknown>) => Promise<Record<string, unknown>>;
}

/**
 * Candidate servers for tool discovery: every server the pipeline knows
 * about, plus every server registered locally.
 *
 * Over-wiring is safe *because* the declared tool list is the real
 * constraint — the agent can only call what the IR named. ROTE_MCP_SERVERS
 * replaces the whole list when an operator needs to point a loop somewhere
 * the pipeline never mentioned.
 */
function agentServerNames(declared: string[]): string[] {
    const override = process.env.ROTE_MCP_SERVERS;
    if (override) {
        return override
            .split(",")
            .map((name) => name.trim())
            .filter(Boolean);
    }
    const names = new Set(declared);
    for (const name of Object.keys(registryServers())) names.add(name);
    return [...names].sort();
}

/**
 * Bind the tools an agent_loop declared to callables the loop can invoke.
 *
 * The IR names tools without servers (one loop may reach several, and an
 * MCPBinding is a single server/tool pair), so discovery walks every
 * candidate server and keeps what matches the declared names.
 *
 * Discovery is best-effort per server: a server that is down or
 * unauthenticated is not necessarily one this loop needed, so it is
 * recorded rather than thrown. A declared tool that no reachable server
 * provides IS fatal — and when an auth failure is the plausible reason,
 * that failure is rethrown so the workflow parks durably and
 * `rote mcp login` can release it, rather than dying with a misleading
 * "no server provides this tool".
 */
export async function bindAgentTools(
    allowed: string[],
    declaredServers: string[],
    serverUrls: Record<string, string | null> = {},
    toolServers: Record<string, string> = {},
): Promise<BoundMcpTool[]> {
    const wanted = new Set(allowed);
    const bound = new Map<string, BoundMcpTool>();
    const failures: unknown[] = [];

    for (const server of agentServerNames(declaredServers)) {
        const url = serverUrls[server] ?? null;
        let specs: McpToolSpec[];
        try {
            specs = await listMcpTools(server, url);
        } catch (err) {
            failures.push(err);
            continue;
        }
        for (const spec of specs) {
            if (!wanted.has(spec.name) || bound.has(spec.name)) continue;
            // A tool the IR resolved to a server binds ONLY from that
            // server: two servers exporting the same tool name is exactly
            // the case an allowlist cannot disambiguate, and silently
            // taking whichever answered first is how a loop ends up
            // talking to the wrong endpoint. Unresolved tools keep the
            // first-wins fallback — there is nothing better to go on.
            const pinned = toolServers[spec.name];
            if (pinned !== undefined && pinned !== server) continue;
            bound.set(spec.name, {
                name: spec.name,
                description: spec.description,
                parameters: spec.inputSchema,
                run: (args) => callMcpTool(server, url, spec.name, args),
            });
        }
    }

    const missing = allowed.filter((name) => !bound.has(name));
    if (missing.length > 0) {
        const authFailure = failures.find((err) => isRoteMcpAuthNeeded(err));
        if (authFailure) throw authFailure;
        const detail = failures
            .map((err) => (err instanceof Error ? err.message : String(err)))
            .join("; ");
        throw new Error(
            `agent tools not provided by any reachable MCP server: ${missing.join(", ")}` +
                (detail ? ` (unreachable: ${detail})` : ""),
        );
    }
    return [...bound.values()];
}

function isUnauthorized(err: unknown): boolean {
    return err instanceof StreamableHTTPError
        ? err.code === 401
        : /\b401\b|[Uu]nauthorized/.test(String(err));
}
