/**
 * Agent loop: lead_generation_loop
 *
 * Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo
 *
 * Auto-generated by rote.adapters.inngest. Bounded at 10 iteration(s)
 * and restricted to the tools below — the agent sees nothing else. Which
 * lane pays for the inference (your Anthropic key, your Cloudflare account,
 * or rote cloud) is resolved at runtime by signatures/_roteInference.ts;
 * ROTE_MODEL_LEAD_GENERATION_LOOP / ROTE_BASE_URL_LEAD_GENERATION_LOOP override the model and endpoint.
 */

import { runAgentLoop, type BoundTool } from "../signatures/_roteInference";
import { bindAgentTools } from "./_roteMcp";
import { enrichContactBatch } from "./enrich_contact_batch";
import { vetContact } from "../signatures/vet_contact";

/** Tools the IR declared for this loop — the allowlist IS the boundary. */
const TOOLS: string[] = ["zoominfo_search_contacts", "zoominfo_search_companies"];

/** Servers searched for those tools, with the endpoints the IR recorded. */
const SERVERS: string[] = ["airweave", "brightdata", "clinicaltrials", "salesforce", "zoominfo"];
const SERVER_URLS: Record<string, string | null> = {"airweave": null, "brightdata": null, "clinicaltrials": null, "salesforce": null, "zoominfo": null};

/** Tools the IR resolved to a specific server — these bind from that
 * server and no other, so two servers exporting one tool name cannot
 * silently swap endpoints. Tools absent here fall back to first-wins
 * across SERVERS. */
const TOOL_SERVERS: Record<string, string> = {"zoominfo_search_companies": "zoominfo", "zoominfo_search_contacts": "zoominfo"};

function requireEnv(name: string): string {
    const value = process.env[name];
    if (!value) {
        throw new Error(`missing required environment variable ${name}`);
    }
    return value;
}

export async function leadGenerationLoop(
    input: unknown,
): Promise<{ result: string; provider: string; iterations: number | null }> {
    const vars = process.env;
    const tools: BoundTool[] = await bindAgentTools(TOOLS, SERVERS, SERVER_URLS, TOOL_SERVERS);
    // loop_body sub-nodes: real pipeline steps, driven per iteration.
    tools.push(
        {
            name: "enrich_contact_batch",
            description: "Batch enrich contacts via ZoomInfo. Always requests employmentHistory\nbecause vetting depends on it. Hard limit of 10 contacts per call\nfrom the ZoomInfo API.",
            parameters: {"type": "object", "additionalProperties": true},
            run: async (args) => enrichContactBatch(args),
        },
        {
            name: "vet_contact",
            description: "Apply the red-flags rubric (MSL, biomarker, translational, indication\nmismatch, sales background, ops/strategy MA, program management) and\nthe core test (\"Would this person commission, design, or approve a\nreal-world evidence study?\"). Discard contacts with accuracy <85.\nTier the keepers as ideal/strong/good.",
            parameters: {"type": "object", "additionalProperties": true},
            run: async (args) => vetContact(args, {
        ANTHROPIC_API_KEY: requireEnv("ANTHROPIC_API_KEY"),
        ROTE_MODEL_VET_CONTACT: process.env.ROTE_MODEL_VET_CONTACT,
        ROTE_BASE_URL_VET_CONTACT: process.env.ROTE_BASE_URL_VET_CONTACT,
    }),
        },
    );
    return runAgentLoop({
        nodeId: "lead_generation_loop",
        description: "Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo\nsearches (ideal persona, manufacturer's internal team, TA broad net).\nEnriches in batches of 10, vets each contact, backfills with new\ntargeted searches when discards create gaps. Loop terminates when the\nvetted-contact quota is met.\n",
        task: input,
        model: vars.ROTE_MODEL_LEAD_GENERATION_LOOP ?? "claude-sonnet-4-6",
        tools,
        maxIterations: 10,
        termination: "vetted_count >= target_quota",
        baseUrl: vars.ROTE_BASE_URL_LEAD_GENERATION_LOOP ?? null,
        env: vars,
    });
}
