/**
 * Agent loop: lead_generation_loop
 *
 * Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo
 *
 * Auto-generated by rote.adapters.dbos_ts. Bounded at 10 iteration(s)
 * and restricted to the tools below — the agent sees nothing else. Which
 * lane pays for the inference (your Anthropic key, your Cloudflare account,
 * or rote cloud) is resolved at runtime by signatures/_roteInference.ts;
 * ROTE_MODEL_LEAD_GENERATION_LOOP / ROTE_BASE_URL_LEAD_GENERATION_LOOP override the model and endpoint.
 */

import { runAgentLoop, type BoundTool } from "../signatures/_roteInference";
import { bindAgentTools } from "./_roteMcp";
import { enrichContactBatch } from "./enrich_contact_batch";
import { vetContact } from "../signatures/vet_contact";

/** Tools the IR declared for this loop — the allowlist IS the boundary. */
const TOOLS: string[] = ["zoominfo_search_contacts", "zoominfo_search_companies"];

// NOTE: no MCP server could be resolved at emit time — this loop's
// tools are bare names and no node in the pipeline carries an `mcp:`
// binding to search. The Node runtimes fall back to every server in
// the local rote registry; set ROTE_MCP_SERVERS to name them
// explicitly (required on Cloudflare, which has no registry).
/** Servers searched for those tools, with the endpoints the IR recorded. */
const SERVERS: string[] = [];
const SERVER_URLS: Record<string, string | null> = {};

function requireEnv(name: string): string {
    const value = process.env[name];
    if (!value) {
        throw new Error(`missing required environment variable ${name}`);
    }
    return value;
}

export async function leadGenerationLoop(
    input: unknown,
): Promise<{ result: string; provider: string; iterations: number | null }> {
    const vars = process.env;
    const tools: BoundTool[] = await bindAgentTools(TOOLS, SERVERS, SERVER_URLS);
    // loop_body sub-nodes: real pipeline steps, driven per iteration.
    tools.push(
        {
            name: "enrich_contact_batch",
            description: "Batch enrich contacts via ZoomInfo. Always requests employmentHistory\nbecause vetting depends on it. Hard limit of 10 contacts per call\nfrom the ZoomInfo API.",
            parameters: {"type": "object", "additionalProperties": true},
            run: async (args) => enrichContactBatch(args),
        },
        {
            name: "vet_contact",
            description: "Apply the red-flags rubric (MSL, biomarker, translational, indication\nmismatch, sales background, ops/strategy MA, program management) and\nthe core test (\"Would this person commission, design, or approve a\nreal-world evidence study?\"). Discard contacts with accuracy <85.\nTier the keepers as ideal/strong/good.",
            parameters: {"type": "object", "additionalProperties": true},
            run: async (args) => vetContact(args, {
        ANTHROPIC_API_KEY: requireEnv("ANTHROPIC_API_KEY"),
        ROTE_MODEL_VET_CONTACT: process.env.ROTE_MODEL_VET_CONTACT,
        ROTE_BASE_URL_VET_CONTACT: process.env.ROTE_BASE_URL_VET_CONTACT,
    }),
        },
    );
    return runAgentLoop({
        nodeId: "lead_generation_loop",
        description: "Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo\nsearches (ideal persona, manufacturer's internal team, TA broad net).\nEnriches in batches of 10, vets each contact, backfills with new\ntargeted searches when discards create gaps. Loop terminates when the\nvetted-contact quota is met.\n",
        task: input,
        model: vars.ROTE_MODEL_LEAD_GENERATION_LOOP ?? "claude-sonnet-4-6",
        tools,
        maxIterations: 10,
        termination: "vetted_count >= target_quota",
        baseUrl: vars.ROTE_BASE_URL_LEAD_GENERATION_LOOP ?? null,
        env: vars,
    });
}
