"""Auto-generated by rote.adapters.dbos.

Pipeline: bdr-campaign v0.1.0
Source skill: ../skill
Pipeline hash: ada0f771

DO NOT EDIT BY HAND. Re-run ``rote emit --runtime dbos`` to regenerate.

Workflow versioning: the registered workflow name includes a hash of
the pipeline so regenerated pipelines become a new workflow type.
In-flight workflows recover onto the code they started with (DBOS
recovers by workflow name + application_version); new starts use the
new code.

Architecture note: every step in this file wraps a deterministic
function from ``extracted/`` or a typed LLM signature from
``signatures/``. None of them call MCP tools at runtime — the MCP
tool calls from the source skill were compiled into direct API
calls during the rote emission step.
"""

from __future__ import annotations

import json
import os
import sys
import threading
from pathlib import Path
from typing import Any

from dbos import DBOS, DBOSConfig, Queue

# ───────── DBOS configuration ─────────
#
# Local dev runs on SQLite (zero infrastructure). Production should
# point DBOS_SYSTEM_DATABASE_URL at Postgres — SQLite is
# single-process only.
_APP_DIR = Path(__file__).resolve().parent

config: DBOSConfig = {
    "name": "bdr-campaign",
    "system_database_url": os.environ.get(
        "DBOS_SYSTEM_DATABASE_URL",
        f"sqlite:///{_APP_DIR / 'bdr-campaign.dbos.sqlite'}",
    ),
    # The admin server (port 3001) is opt-in; enable it when you
    # want the DBOS console / management API.
    "run_admin_server": False,
}
DBOS(config=config)

# Parallel waves fan out onto this queue; each enqueued step runs as
# a one-step workflow with its own durable handle.
queue = Queue("bdr-campaign-queue")


def _serialize(obj: Any) -> Any:
    """Convert pydantic models / tuples to plain JSON-safe values.

    Steps return JSON-serializable payloads so workflow state stays
    portable across the system database.
    """
    if hasattr(obj, "model_dump"):
        return obj.model_dump(by_alias=True)
    if isinstance(obj, (list, tuple)):
        return [_serialize(x) for x in obj]
    if isinstance(obj, dict):
        return {k: _serialize(v) for k, v in obj.items()}
    return obj


def _fan_out_list(value: object, node_id: str, ref: str) -> list:
    """The list a fan_out node dispatches over.

    Iterating a missing key raises "'NoneType' object is not iterable",
    which names neither the node nor the reference — in generated code
    that is close to undebuggable, and the cause is almost always an
    upstream node that didn't return the key the IR says it does. The
    TypeScript runtimes emit the same guard (`fanOutList`), so a missing
    key reports identically on every target.
    """
    if not isinstance(value, list):
        raise TypeError(
            f"fan_out node {node_id!r} expected a list from {ref!r}, got "
            f"{type(value).__name__}. The upstream node must return that "
            f"key as a list."
        )
    return value


@DBOS.step(name="target_research", retries_allowed=True, max_attempts=3, backoff_rate=2.0)
def target_research(payload: dict) -> dict:
    """Run external research (Bright Data web search, ClinicalTrials.gov)

    Agent loop — bounded, tool-restricted, and real: the provider
    (Claude subscription / API key / rote cloud) is resolved at
    runtime by signatures/_rote_inference.py.
    """
    # IR timeout '5m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures._rote_inference import run_agent_loop

    return run_agent_loop(
        node_id="target_research",
        description=(
            "Run external research (Bright Data web search, ClinicalTrials.gov)\nand inte"
            "rnal research (Airweave enterprise search, Salesforce account\nhistory, inte"
            "rnal publications) in parallel. Compile a short intel\nbrief covering pipeli"
            "ne, RWE/HEOR signals, key programs/teams, prior\naccount interactions, and v"
            "alidated TA experience.\n"
        ),
        task=json.dumps(payload, default=str),
        model=os.environ.get("ROTE_MODEL_TARGET_RESEARCH", "claude-sonnet-4-6"),
        tools=[
            "bright_data_search",
            "bright_data_scrape",
            "clinical_trials_search",
            "airweave_search",
            "salesforce_query",
        ],
        tool_servers={"airweave_search": "airweave", "bright_data_scrape": "brightdata", "bright_data_search": "brightdata", "clinical_trials_search": "clinicaltrials", "salesforce_query": "salesforce"},
        max_iterations=10,
    )


@DBOS.step(name="taxonomy_lookup")
def taxonomy_lookup(payload: dict) -> dict:
    """Resolve ZoomInfo IDs for management levels (VP, Director), industries

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.taxonomy`` for the implementation.
    """
    from extracted.taxonomy import resolve_taxonomy_ids

    return _serialize(resolve_taxonomy_ids(**payload))


@DBOS.step(name="lead_generation_loop")
def lead_generation_loop(payload: dict) -> dict:
    """Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo

    Agent loop — bounded, tool-restricted, and real: the provider
    (Claude subscription / API key / rote cloud) is resolved at
    runtime by signatures/_rote_inference.py.
    """
    # IR timeout '15m': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from signatures._rote_inference import run_agent_loop

    return run_agent_loop(
        node_id="lead_generation_loop",
        description=(
            "Iterative search-enrich-vet loop. Starts with three parallel ZoomInfo\nsearc"
            "hes (ideal persona, manufacturer's internal team, TA broad net).\nEnriches i"
            "n batches of 10, vets each contact, backfills with new\ntargeted searches wh"
            "en discards create gaps. Loop terminates when the\nvetted-contact quota is m"
            "et.\n"
        ),
        task=json.dumps(payload, default=str),
        model=os.environ.get("ROTE_MODEL_LEAD_GENERATION_LOOP", "claude-sonnet-4-6"),
        tools=["zoominfo_search_contacts", "zoominfo_search_companies"],
        tool_servers={"zoominfo_search_companies": "zoominfo", "zoominfo_search_contacts": "zoominfo"},
        local_tools={
            "enrich_contact_batch": enrich_contact_batch,
            "vet_contact": vet_contact,
        },
        max_iterations=10,
        termination="vetted_count >= target_quota",
    )


@DBOS.step(name="enrich_contact_batch", retries_allowed=True, max_attempts=6, backoff_rate=2.0)
def enrich_contact_batch(payload: dict) -> dict:
    """Batch enrich contacts via ZoomInfo. Always requests employmentHistory

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.zoominfo`` for the implementation.
    """
    # retry_on categories from the IR: rate_limit, network. DBOS retries any
    # exception; narrow with @DBOS.step(should_retry=...) if needed.
    # IR timeout '30s': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.zoominfo import enrich_batch

    return _serialize(enrich_batch(**payload))


@DBOS.step(name="vet_contact")
def vet_contact(payload: dict) -> dict:
    """Apply the red-flags rubric (MSL, biomarker, translational, indication

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this step, not the workflow.
    """
    from signatures.vet_contact import VetContact, VetContactInput

    judge = VetContact()
    return judge.forward(VetContactInput(**payload)).model_dump(by_alias=True)


@DBOS.step(name="hubspot_upsert", retries_allowed=True, max_attempts=6, backoff_rate=2.0)
def hubspot_upsert(payload: dict) -> dict:
    """Batch upsert contacts to HubSpot (create or update by email). Hard

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.hubspot`` for the implementation.
    """
    # IR timeout '60s': DBOS has no per-step timeout
    # primitive; enforce inside the implementation if required.
    from extracted.hubspot import batch_upsert_contacts

    return _serialize(batch_upsert_contacts(**payload))


@DBOS.step(name="hubspot_create_list", retries_allowed=True, max_attempts=6, backoff_rate=2.0)
def hubspot_create_list(payload: dict) -> dict:
    """Create a static list named after the campaign and add the upserted

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.hubspot`` for the implementation.
    """
    from extracted.hubspot import create_campaign_list

    return _serialize(create_campaign_list(**payload))


@DBOS.step(name="exclusion_check_dnc")
def exclusion_check_dnc(payload: dict) -> dict:
    """For each contact, look up \"BDR do not contact\" list memberships.

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.exclusion_checks`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    from extracted.exclusion_checks import check_do_not_contact

    return _serialize(check_do_not_contact(**payload))


@DBOS.step(name="exclusion_check_recent")
def exclusion_check_recent(payload: dict) -> dict:
    """For each contact, check if they were emailed (outbound) in the last

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.exclusion_checks`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    from extracted.exclusion_checks import check_recently_emailed

    return _serialize(check_recently_emailed(**payload))


@DBOS.step(name="exclusion_check_sequence")
def exclusion_check_sequence(payload: dict) -> dict:
    """For each contact, check if they are already enrolled in an active

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.exclusion_checks`` for the implementation.
    """
    # MANDATORY: this node was marked mandatory in the source
    # skill. The workflow always calls it; do not make it conditional.
    from extracted.exclusion_checks import check_active_sequence

    return _serialize(check_active_sequence(**payload))


@DBOS.step(name="personalize_email")
def personalize_email(payload: dict) -> dict:
    """Generate personalized opening line and TA-relevant callout per

    LLM judge — typed input/output, bounded decision space. The
    non-determinism lives inside this step, not the workflow.
    """
    from signatures.personalize_email import PersonalizeEmail, PersonalizeEmailInput

    judge = PersonalizeEmail()
    return judge.forward(PersonalizeEmailInput(**payload)).model_dump(by_alias=True)


@DBOS.step(name="create_sales_template", retries_allowed=True, max_attempts=4, backoff_rate=2.0)
def create_sales_template(payload: dict) -> dict:
    """Create or update HubSpot sales templates for the campaign sequence

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.hubspot`` for the implementation.
    """
    from extracted.hubspot import upsert_sales_template

    return _serialize(upsert_sales_template(**payload))


@DBOS.step(name="pre_enrollment_report")
def pre_enrollment_report(payload: dict) -> dict:
    """Generate the final pre-enrollment report (markdown) with totals,

    Compiled from MCP tool call → deterministic API call. See
    ``extracted.report`` for the implementation.
    """
    from extracted.report import generate_pre_enrollment_report

    return _serialize(generate_pre_enrollment_report(**payload))


@DBOS.workflow(name="BdrCampaign_ada0f771")
def run_pipeline(pipeline_input: dict) -> dict:
    """End-to-end BDR outreach campaign workflow for pharma/biotech research"""

    # ─── Wave 1 ───
    # Parallel fan-out: enqueue every node in the wave, then
    # join. Each enqueued step runs as its own one-step
    # workflow; get_result() blocks durably.
    target_research_handle = queue.enqueue(
        target_research,
        {
            "brief": pipeline_input,
        },
    )
    taxonomy_lookup_handle = queue.enqueue(
        taxonomy_lookup,
        {
            "brief": pipeline_input,
        },
    )
    target_research_result = target_research_handle.get_result()
    taxonomy_lookup_result = taxonomy_lookup_handle.get_result()

    # ─── Wave 2 ───
    lead_generation_loop_result = lead_generation_loop(
        {
            "brief": pipeline_input,
            "intel": target_research_result,
            "taxonomy": taxonomy_lookup_result,
            "target_quota": pipeline_input["target_quota"],
        }
    )

    # ─── Wave 3 ───
    # ─── HITL gate: contact_review_gate ───
    # Durable receive: the workflow parks in the system database until
    # DBOS.send(workflow_id, payload, topic='contact_review_approved')
    # delivers the resume message. Survives process restarts.
    contact_review_gate_result = DBOS.recv(
        topic="contact_review_approved",
        timeout_seconds=604800,  # 7d
    )
    if contact_review_gate_result is None:
        raise TimeoutError(
            "HITL gate 'contact_review_gate' timed out after 7d waiting "
            "for signal 'contact_review_approved'"
        )

    # ─── Wave 4 ───
    hubspot_upsert_result = hubspot_upsert(
        {
            "contacts": contact_review_gate_result["approved_contacts"],
        }
    )

    # ─── Wave 5 ───
    hubspot_create_list_result = hubspot_create_list(
        {
            "campaign_name": pipeline_input["drug_brand"],
            "contacts": hubspot_upsert_result["upserted"],
        }
    )

    # ─── Wave 6 ───
    exclusion_check_dnc_result = exclusion_check_dnc(
        {
            "contacts": hubspot_upsert_result["upserted"],
        }
    )

    # ─── Wave 7 ───
    exclusion_check_recent_result = exclusion_check_recent(
        {
            "contacts": exclusion_check_dnc_result["passed"],
        }
    )

    # ─── Wave 8 ───
    exclusion_check_sequence_result = exclusion_check_sequence(
        {
            "contacts": exclusion_check_recent_result["passed"],
        }
    )

    # ─── Wave 9 ───
    # fan_out: personalize_email runs once per element of the bound
    # list, each as its own enqueued durable step.
    personalize_email_payloads = [
        {"contact": _item, "campaign_type": pipeline_input["campaign_type"], "intel": target_research_result}
        for _item in _fan_out_list(
            exclusion_check_sequence_result["passed"],
            "personalize_email",
            "exclusion_check_sequence.output.passed",
        )
    ]
    personalize_email_handles = [queue.enqueue(personalize_email, _p) for _p in personalize_email_payloads]
    personalize_email_result = [_h.get_result() for _h in personalize_email_handles]

    # ─── Wave 10 ───
    create_sales_template_result = create_sales_template(
        {
            "campaign_name": pipeline_input["drug_brand"],
            "personalizations": personalize_email_result,
        }
    )

    # ─── Wave 11 ───
    pre_enrollment_report_result = pre_enrollment_report(
        {
            "campaign_name": pipeline_input["drug_brand"],
            "passed_contacts": exclusion_check_sequence_result["passed"],
            "exclusions": exclusion_check_sequence_result["excluded"],
            "template_ids": create_sales_template_result["template_ids"],
        }
    )

    # ─── Wave 12 ───
    # ─── HITL gate: manual_enrollment_handoff ───
    # Durable receive: the workflow parks in the system database until
    # DBOS.send(workflow_id, payload, topic='bdr_enrollment_complete')
    # delivers the resume message. Survives process restarts.
    manual_enrollment_handoff_result = DBOS.recv(
        topic="bdr_enrollment_complete",
        timeout_seconds=1209600,  # 14d
    )
    if manual_enrollment_handoff_result is None:
        raise TimeoutError(
            "HITL gate 'manual_enrollment_handoff' timed out after 14d waiting "
            "for signal 'bdr_enrollment_complete'"
        )

    return {
        "manual_enrollment_handoff": manual_enrollment_handoff_result,
    }


if __name__ == "__main__":
    # Launch DBOS (connects to the system database, starts queue
    # workers and recovery). Two modes:
    #
    #   python main.py --serve
    #       Run as a long-lived worker: execute runs enqueued
    #       externally (`rote serve` MCP tools / DBOSClient.enqueue)
    #       against the same system database. This is what
    #       `dbos start` and production deployments run.
    #
    #   python main.py '{"your": "input"}'
    #       Start one pipeline run with the input from argv[1]
    #       (JSON) and block until it completes.
    #
    # HITL gates are resumed from another process either way — see
    # README.md.
    DBOS.launch()
    try:
        if "--serve" in sys.argv[1:]:
            print("serving: waiting for enqueued runs (Ctrl-C to stop)", file=sys.stderr)
            threading.Event().wait()
        else:
            pipeline_input = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
            handle = DBOS.start_workflow(run_pipeline, pipeline_input)
            print(f"workflow started: {handle.workflow_id}", file=sys.stderr)
            print(json.dumps(handle.get_result(), indent=2, default=str))
    finally:
        DBOS.destroy()
